window.PRICES_DATA = {
  "updated": "2026-09-16 07:31",
  "fx_gbp_usd": 1.348,
  "stocks": [
    {
      "ticker": "LMT",
      "company_name": "Lockheed Martin",
      "category": "us-primes",
      "exchange": "NYSE",
      "price_gbp": "396",
      "price_usd": 533.46,
      "change_1d": "+0.56%",
      "change_1w": "-0.50%",
      "change_1m": "-9.60%",
      "change_ytd": "+9.26%",
      "return_1yr": "+12%",
      "low_gbp": "324",
      "low_usd": 437.25,
      "high_gbp": "513",
      "high_usd": 692.0,
      "bar_pct": 38,
      "market_cap_gbp_b": 91.334,
      "market_cap_usd_b": 123.118,
      "beta": 0.104,
      "pe_ratio": 19.53,
      "avg_volume_m": 1.21,
      "div_yield_pct": 261.0,
      "short_pct": 1.39,
      "analyst": "buy",
      "analyst_score": 2.43,
      "vol_1d": 918100,
      "vol_1w": 5567600,
      "vol_1m": 22423700,
      "news": [
        {
          "title": "Space Weapons: How Boeing, SpaceX, and Others Stand to Gain",
          "publisher": "Barrons.com",
          "url": "https://www.barrons.com/articles/us-space-force-weapons-defense-stocks-297a15eb?siteid=yhoof2&yptr=yahoo",
          "published": 1789505940,
          "sentiment": 0.128
        },
        {
          "title": "Why Is Boeing Stock Falling While Revenue Soars Past Peers?",
          "publisher": "Trefis",
          "url": "https://www.trefis.com/articles/615375/why-is-boeing-stock-falling-while-revenue-soars-past-peers/2026-09-15",
          "published": 1789493945,
          "sentiment": -0.153
        },
        {
          "title": "What Has To Go Right For GE Stock To Keep Climbing?",
          "publisher": "Trefis",
          "url": "https://www.trefis.com/articles/615380/what-has-to-go-right-for-ge-stock-to-keep-climbing/2026-09-15",
          "published": 1789492706,
          "sentiment": 0.0
        },
        {
          "title": "Can Rising KC-46 Demand Strengthen Boeing's Defense Growth?",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/rising-kc-46-demand-strengthen-143200466.html",
          "published": 1789482720,
          "sentiment": 0.599
        },
        {
          "title": "Lockheed Martin Corporation (LMT) Is a Trending Stock: Facts to Know Before Betting on It",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/lockheed-martin-corporation-lmt-trending-130003024.html",
          "published": 1789390803,
          "sentiment": 0.0
        }
      ],
      "news_sentiment": 0.115
    },
    {
      "ticker": "RTX",
      "company_name": "RTX Corporation",
      "category": "us-primes",
      "exchange": "NYSE",
      "price_gbp": "145",
      "price_usd": 195.5,
      "change_1d": "+0.07%",
      "change_1w": "-1.66%",
      "change_1m": "-11.79%",
      "change_ytd": "+5.54%",
      "return_1yr": "+23%",
      "low_gbp": "115",
      "low_usd": 155.64,
      "high_gbp": "168",
      "high_usd": 226.88,
      "bar_pct": 56,
      "market_cap_gbp_b": 195.465,
      "market_cap_usd_b": 263.487,
      "beta": 0.287,
      "pe_ratio": 34.36,
      "avg_volume_m": 4.68,
      "div_yield_pct": 149.0,
      "short_pct": 0.92,
      "analyst": "buy",
      "analyst_score": 1.87,
      "vol_1d": 4728200,
      "vol_1w": 17956900,
      "vol_1m": 85627200,
      "news": [
        {
          "title": "RTX Highlights $289B Backlog as Aerospace, Defense Demand Powers Growth",
          "publisher": "MarketBeat",
          "url": "https://www.marketbeat.com/instant-alerts/event-rtx-highlights-289b-backlog-as-aerospace-defense-demand-powers-growth-2026-09-15/?utm_source=yahoofinance&utm_medium=yahoofinance",
          "published": 1789520529,
          "sentiment": 0.382
        },
        {
          "title": "Boeing (BA) and RTX (RTX) Gain From Pentagon Missile Buildup, But Is the Upside Priced In?",
          "publisher": "Insider Monkey",
          "url": "https://finance.yahoo.com/markets/stocks/articles/boeing-ba-rtx-rtx-gain-193701338.html",
          "published": 1789501021,
          "sentiment": 0.296
        },
        {
          "title": "Surging Oil Prices Singe GE Aerospace",
          "publisher": "The Wall Street Journal",
          "url": "https://www.wsj.com/livecoverage/stock-market-today-dow-sp-500-nasdaq-09-15-2026/card/surging-oil-prices-singe-ge-aerospace-lMlfR7Aab53uw3Mcrs9p?siteid=yhoof2&yptr=yahoo",
          "published": 1789495101,
          "sentiment": 0.0
        },
        {
          "title": "Why Is Boeing Stock Falling While Revenue Soars Past Peers?",
          "publisher": "Trefis",
          "url": "https://www.trefis.com/articles/615375/why-is-boeing-stock-falling-while-revenue-soars-past-peers/2026-09-15",
          "published": 1789493945,
          "sentiment": -0.153
        },
        {
          "title": "What Has To Go Right For GE Stock To Keep Climbing?",
          "publisher": "Trefis",
          "url": "https://www.trefis.com/articles/615380/what-has-to-go-right-for-ge-stock-to-keep-climbing/2026-09-15",
          "published": 1789492706,
          "sentiment": 0.0
        }
      ],
      "news_sentiment": 0.105
    },
    {
      "ticker": "NOC",
      "company_name": "Northrop Grumman",
      "category": "us-primes",
      "exchange": "NYSE",
      "price_gbp": "394",
      "price_usd": 531.25,
      "change_1d": "+0.73%",
      "change_1w": "+2.44%",
      "change_1m": "-6.41%",
      "change_ytd": "-8.18%",
      "return_1yr": "-9%",
      "low_gbp": "355",
      "low_usd": 479.02,
      "high_gbp": "574",
      "high_usd": 774.0,
      "bar_pct": 18,
      "market_cap_gbp_b": 55.987,
      "market_cap_usd_b": 75.47,
      "beta": -0.11,
      "pe_ratio": 16.75,
      "avg_volume_m": 0.88,
      "div_yield_pct": 187.0,
      "short_pct": 1.68,
      "analyst": "buy",
      "analyst_score": 2.0,
      "vol_1d": 771200,
      "vol_1w": 3879000,
      "vol_1m": 15917300,
      "news": [
        {
          "title": "Northrop Grumman (NOC) Stock May Be 21% Undervalued Following Sentinel Missile Progress",
          "publisher": "Simply Wall St.",
          "url": "https://finance.yahoo.com/markets/stocks/articles/northrop-grumman-noc-stock-may-001813845.html",
          "published": 1789517893,
          "sentiment": 0.421
        },
        {
          "title": "Northrop Grumman (NOC) Secures $4.8 Billion Army Contract. Execution Is the Bigger Test",
          "publisher": "Insider Monkey",
          "url": "https://finance.yahoo.com/markets/stocks/articles/northrop-grumman-noc-secures-4-203934378.html",
          "published": 1789504774,
          "sentiment": 0.318
        },
        {
          "title": "Why Is Boeing Stock Falling While Revenue Soars Past Peers?",
          "publisher": "Trefis",
          "url": "https://www.trefis.com/articles/615375/why-is-boeing-stock-falling-while-revenue-soars-past-peers/2026-09-15",
          "published": 1789493945,
          "sentiment": -0.153
        },
        {
          "title": "What Has To Go Right For GE Stock To Keep Climbing?",
          "publisher": "Trefis",
          "url": "https://www.trefis.com/articles/615380/what-has-to-go-right-for-ge-stock-to-keep-climbing/2026-09-15",
          "published": 1789492706,
          "sentiment": 0.0
        },
        {
          "title": "This Stock Can Rise 150%, Plus 12 More Aerospace Buys",
          "publisher": "Barrons.com",
          "url": "https://www.barrons.com/articles/defense-stock-buys-guggenheim-northrop-grumman-8b568e43?siteid=yhoof2&yptr=yahoo",
          "published": 1789487820,
          "sentiment": 0.0
        }
      ],
      "news_sentiment": 0.117
    },
    {
      "ticker": "GD",
      "company_name": "General Dynamics",
      "category": "us-primes",
      "exchange": "NYSE",
      "price_gbp": "266",
      "price_usd": 358.6,
      "change_1d": "+1.39%",
      "change_1w": "+0.57%",
      "change_1m": "-8.32%",
      "change_ytd": "+5.80%",
      "return_1yr": "+10%",
      "low_gbp": "228",
      "low_usd": 306.77,
      "high_gbp": "297",
      "high_usd": 400.0,
      "bar_pct": 56,
      "market_cap_gbp_b": 71.975,
      "market_cap_usd_b": 97.022,
      "beta": 0.321,
      "pe_ratio": 21.73,
      "avg_volume_m": 1.14,
      "div_yield_pct": 178.0,
      "short_pct": 1.14,
      "analyst": "buy",
      "analyst_score": 2.08,
      "vol_1d": 1259000,
      "vol_1w": 5270700,
      "vol_1m": 20765400,
      "news": [
        {
          "title": "Why Is Boeing Stock Falling While Revenue Soars Past Peers?",
          "publisher": "Trefis",
          "url": "https://www.trefis.com/articles/615375/why-is-boeing-stock-falling-while-revenue-soars-past-peers/2026-09-15",
          "published": 1789493945,
          "sentiment": -0.153
        },
        {
          "title": "General Dynamics (GD) Upgraded to Buy: Here's Why",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/general-dynamics-gd-upgraded-buy-160004729.html",
          "published": 1789488004,
          "sentiment": 0.273
        },
        {
          "title": "Is General Dynamics (GD) Stock Outpacing Its Aerospace Peers This Year?",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/general-dynamics-gd-stock-outpacing-134004498.html",
          "published": 1789479604,
          "sentiment": 0.273
        },
        {
          "title": "Can Next-Generation Electronic Warfare Drive General Dynamics' Growth?",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/next-generation-electronic-warfare-drive-134000421.html",
          "published": 1789393200,
          "sentiment": 0.361
        },
        {
          "title": "3 S&P 500 Stocks with Warning Signs",
          "publisher": "StockStory",
          "url": "https://finance.yahoo.com/markets/stocks/articles/3-p-500-stocks-warning-170705317.html",
          "published": 1789146425,
          "sentiment": -0.34
        }
      ],
      "news_sentiment": 0.083
    },
    {
      "ticker": "HII",
      "company_name": "Huntington Ingalls Industries",
      "category": "us-primes",
      "exchange": "NYSE",
      "price_gbp": "207",
      "price_usd": 279.46,
      "change_1d": "-0.20%",
      "change_1w": "-2.85%",
      "change_1m": "-11.80%",
      "change_ytd": "-19.13%",
      "return_1yr": "+3%",
      "low_gbp": "196",
      "low_usd": 263.62,
      "high_gbp": "341",
      "high_usd": 460.0,
      "bar_pct": 8,
      "market_cap_gbp_b": 8.169,
      "market_cap_usd_b": 11.012,
      "beta": 0.225,
      "pe_ratio": 16.66,
      "avg_volume_m": 0.48,
      "div_yield_pct": 197.0,
      "short_pct": 3.31,
      "analyst": "none",
      "analyst_score": null,
      "vol_1d": 416100,
      "vol_1w": 1958500,
      "vol_1m": 8221100,
      "news": [
        {
          "title": "Can Growing ISR Demand Strengthen HII's Mission Technologies Business?",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/growing-isr-demand-strengthen-hiis-142500373.html",
          "published": 1789482300,
          "sentiment": 0.361
        },
        {
          "title": "1 of Wall Street\u2019s Favorite Stocks with Promising Prospects and 2 Facing Challenges",
          "publisher": "StockStory",
          "url": "https://finance.yahoo.com/markets/stocks/articles/1-wall-street-favorite-stocks-124104505.html",
          "published": 1789044064,
          "sentiment": 0.802
        },
        {
          "title": "1 S&P 500 Stock with Exciting Potential and 2 We Ignore",
          "publisher": "StockStory",
          "url": "https://finance.yahoo.com/markets/stocks/articles/1-p-500-stock-exciting-232718587.html",
          "published": 1788910038,
          "sentiment": 0.178
        },
        {
          "title": "Redwire Climbs 14.3% in Six Months: Is the Stock Still a Buy?",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/redwire-climbs-14-3-six-133100825.html",
          "published": 1788528660,
          "sentiment": 0.0
        },
        {
          "title": "ACHR Rallies 14.9% in a Month: Should You Buy, Sell or Hold the Stock?",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/achr-rallies-14-9-month-140300555.html",
          "published": 1788357780,
          "sentiment": 0.0
        }
      ],
      "news_sentiment": 0.268
    },
    {
      "ticker": "LHX",
      "company_name": "L3Harris Technologies",
      "category": "us-primes",
      "exchange": "NYSE",
      "price_gbp": "185",
      "price_usd": 249.66,
      "change_1d": "+0.29%",
      "change_1w": "-2.38%",
      "change_1m": "-9.89%",
      "change_ytd": "-16.99%",
      "return_1yr": "-12%",
      "low_gbp": "182",
      "low_usd": 244.76,
      "high_gbp": "281",
      "high_usd": 379.23,
      "bar_pct": 4,
      "market_cap_gbp_b": 34.488,
      "market_cap_usd_b": 46.49,
      "beta": 0.746,
      "pe_ratio": 25.12,
      "avg_volume_m": 1.62,
      "div_yield_pct": 201.0,
      "short_pct": 2.44,
      "analyst": "buy",
      "analyst_score": 1.79,
      "vol_1d": 1445200,
      "vol_1w": 8641700,
      "vol_1m": 35673600,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "BA",
      "company_name": "Boeing",
      "category": "us-primes",
      "exchange": "NYSE",
      "price_gbp": "156",
      "price_usd": 209.69,
      "change_1d": "-0.27%",
      "change_1w": "-0.49%",
      "change_1m": "-7.20%",
      "change_ytd": "-7.94%",
      "return_1yr": "-2%",
      "low_gbp": "131",
      "low_usd": 176.77,
      "high_gbp": "189",
      "high_usd": 254.35,
      "bar_pct": 42,
      "market_cap_gbp_b": 122.947,
      "market_cap_usd_b": 165.733,
      "beta": 1.213,
      "pe_ratio": 75.7,
      "avg_volume_m": 5.51,
      "div_yield_pct": null,
      "short_pct": 0.01,
      "analyst": "buy",
      "analyst_score": 1.54,
      "vol_1d": 3594300,
      "vol_1w": 20111500,
      "vol_1m": 107034900,
      "news": [
        {
          "title": "Boeing Engineers Rejected a New Pay Deal. A 60-Year-Old\u2019s Frozen Pension Could Still Rise With His Salary.",
          "publisher": "24/7 Wall St.",
          "url": "https://247wallst.com/personal-finance/social-security/2026/09/15/boeing-engineers-rejected-a-new-pay-deal-a-60-year-olds-frozen-pension-could-still-rise-with-his-salary/",
          "published": 1789517071,
          "sentiment": -0.572
        },
        {
          "title": "Boeing vs. Space Exploration Technologies: Which Flight Giant Is a Better Buy in 2026?",
          "publisher": "Motley Fool",
          "url": "https://www.fool.com/coverage/better-buy/2026/09/15/boeing-vs-space-exploration-technologies-which-flight-giant-is-a-better-buy-in-2026/",
          "published": 1789506361,
          "sentiment": 0.586
        },
        {
          "title": "Space Weapons: How Boeing, SpaceX, and Others Stand to Gain",
          "publisher": "Barrons.com",
          "url": "https://www.barrons.com/articles/us-space-force-weapons-defense-stocks-297a15eb?siteid=yhoof2&yptr=yahoo",
          "published": 1789505940,
          "sentiment": 0.128
        },
        {
          "title": "Boeing vs. Redwire: Which Aerospace Stock Is a Better Buy in 2026?",
          "publisher": "Motley Fool",
          "url": "https://www.fool.com/coverage/better-buy/2026/09/15/boeing-vs-redwire-which-aerospace-stock-is-a-better-buy-in-2026/",
          "published": 1789504681,
          "sentiment": 0.44
        },
        {
          "title": "Pentagon Adds $13.4 Billion to Boeing (BA) Contract. That Isn\u2019t an Immediate Financial Windfall",
          "publisher": "Insider Monkey",
          "url": "https://finance.yahoo.com/markets/stocks/articles/pentagon-adds-13-4-billion-203602021.html",
          "published": 1789504562,
          "sentiment": 0.0
        }
      ],
      "news_sentiment": 0.116
    },
    {
      "ticker": "BA.L",
      "company_name": "BAE Systems",
      "category": "uk-european",
      "exchange": "LSE",
      "price_gbp": "20",
      "price_usd": 27.04,
      "change_1d": "+3.40%",
      "change_1w": "+3.22%",
      "change_1m": "-10.29%",
      "change_ytd": "+14.38%",
      "return_1yr": "-1%",
      "low_gbp": "14",
      "low_usd": 18.93,
      "high_gbp": "24",
      "high_usd": 31.81,
      "bar_pct": 50,
      "market_cap_gbp_b": 0.587,
      "market_cap_usd_b": 0.791,
      "beta": -0.057,
      "pe_ratio": 28.66,
      "avg_volume_m": 6.23,
      "div_yield_pct": 195.0,
      "short_pct": null,
      "analyst": "buy",
      "analyst_score": 2.25,
      "vol_1d": 181125,
      "vol_1w": 20977970,
      "vol_1m": 102635775,
      "news": [
        {
          "title": "European Indexes Slide as Higher Oil Weighs on Defense Stocks, Banks",
          "publisher": "The Wall Street Journal",
          "url": "https://www.wsj.com/finance/stocks/nikkei-rises-0-1-led-by-chip-related-stocks-c8902c64?siteid=yhoof2&yptr=yahoo",
          "published": 1788939540,
          "sentiment": 0.128
        },
        {
          "title": "Griffin Mining And 2 British Defensive Stocks",
          "publisher": "Simply Wall St.",
          "url": "https://finance.yahoo.com/markets/stocks/articles/griffin-mining-2-british-defensive-141521867.html",
          "published": 1788531321,
          "sentiment": 0.026
        },
        {
          "title": "BP Names Ian Tyler Permanent Chair After Manifold\u2019s Abrupt Exit",
          "publisher": "Oilprice.com",
          "url": "https://finance.yahoo.com/energy/articles/bp-names-ian-tyler-permanent-065000654.html",
          "published": 1788331800,
          "sentiment": 0.0
        },
        {
          "title": "BAE Systems Stock And 2 Cash Flow Value Shares Worth A Closer Look",
          "publisher": "Simply Wall St.",
          "url": "https://finance.yahoo.com/markets/stocks/articles/bae-systems-stock-2-cash-161713632.html",
          "published": 1788193033,
          "sentiment": 0.67
        },
        {
          "title": "Can Viper Shield Expand L3Harris' Electronic Warfare Growth?",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/viper-shield-expand-l3harris-electronic-151000190.html",
          "published": 1787929800,
          "sentiment": 0.402
        }
      ],
      "news_sentiment": 0.245
    },
    {
      "ticker": "RR.L",
      "company_name": "Rolls-Royce Holdings",
      "category": "uk-european",
      "exchange": "LSE",
      "price_gbp": "14",
      "price_usd": 19.14,
      "change_1d": "-0.25%",
      "change_1w": "-4.11%",
      "change_1m": "-9.18%",
      "change_ytd": "+18.66%",
      "return_1yr": "+28%",
      "low_gbp": "9.94",
      "low_usd": 13.4,
      "high_gbp": "16",
      "high_usd": 21.38,
      "bar_pct": 50,
      "market_cap_gbp_b": 1.17,
      "market_cap_usd_b": 1.577,
      "beta": 1.188,
      "pe_ratio": 39.45,
      "avg_volume_m": 20.67,
      "div_yield_pct": 84.0,
      "short_pct": null,
      "analyst": "none",
      "analyst_score": null,
      "vol_1d": 2729944,
      "vol_1w": 58164462,
      "vol_1m": 280005634,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "QQ.L",
      "company_name": "QinetiQ Group",
      "category": "uk-european",
      "exchange": "LSE",
      "price_gbp": "4.90",
      "price_usd": 6.6,
      "change_1d": "+1.58%",
      "change_1w": "+2.56%",
      "change_1m": "-12.10%",
      "change_ytd": "+10.20%",
      "return_1yr": "-5%",
      "low_gbp": "3.43",
      "low_usd": 4.62,
      "high_gbp": "5.76",
      "high_usd": 7.77,
      "bar_pct": 50,
      "market_cap_gbp_b": 0.025,
      "market_cap_usd_b": 0.034,
      "beta": 0.342,
      "pe_ratio": 24.48,
      "avg_volume_m": 2.02,
      "div_yield_pct": 228.0,
      "short_pct": null,
      "analyst": "buy",
      "analyst_score": 1.75,
      "vol_1d": 104234,
      "vol_1w": 4947624,
      "vol_1m": 27912330,
      "news": [
        {
          "title": "Gelion battery cells pass independent drone testing at QinetiQ",
          "publisher": "Proactive",
          "url": "https://www.proactiveinvestors.com/companies/news/1097611/gelion-battery-cells-pass-independent-drone-testing-at-qinetiq-1097611.html",
          "published": 1787725920,
          "sentiment": 0.0
        },
        {
          "title": "3 UK Penny Stocks With Market Caps Over \u00a3300M To Consider",
          "publisher": "Simply Wall St.",
          "url": "https://finance.yahoo.com/markets/stocks/articles/3-uk-penny-stocks-market-070513783.html",
          "published": 1781161513,
          "sentiment": 0.0
        },
        {
          "title": "UK Growth Stocks With Insider Ownership Up To 20%",
          "publisher": "Simply Wall St.",
          "url": "https://finance.yahoo.com/markets/stocks/articles/uk-growth-stocks-insider-ownership-063529243.html",
          "published": 1781159729,
          "sentiment": 0.382
        },
        {
          "title": "UK Stocks That May Be Trading Below Fair Value In June 2026",
          "publisher": "Simply Wall St.",
          "url": "https://finance.yahoo.com/markets/stocks/articles/uk-stocks-may-trading-below-063814407.html",
          "published": 1780382294,
          "sentiment": 0.572
        },
        {
          "title": "Top UK Growth Companies With High Insider Ownership In May 2026",
          "publisher": "Simply Wall St.",
          "url": "https://finance.yahoo.com/markets/stocks/articles/top-uk-growth-companies-high-063531772.html",
          "published": 1779431731,
          "sentiment": 0.527
        }
      ],
      "news_sentiment": 0.296
    },
    {
      "ticker": "PLTR",
      "company_name": "Palantir Technologies",
      "category": "cyber-intel",
      "exchange": "NASDAQ",
      "price_gbp": "128",
      "price_usd": 172.56,
      "change_1d": "-0.22%",
      "change_1w": "+1.33%",
      "change_1m": "+0.01%",
      "change_ytd": "+2.80%",
      "return_1yr": "+3%",
      "low_gbp": "79",
      "low_usd": 106.37,
      "high_gbp": "154",
      "high_usd": 207.52,
      "bar_pct": 65,
      "market_cap_gbp_b": 307.62,
      "market_cap_usd_b": 414.672,
      "beta": 1.621,
      "pe_ratio": 147.49,
      "avg_volume_m": 40.19,
      "div_yield_pct": null,
      "short_pct": 3.03,
      "analyst": "buy",
      "analyst_score": 1.81,
      "vol_1d": 31204200,
      "vol_1w": 117451600,
      "vol_1m": 608785200,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "LDOS",
      "company_name": "Leidos Holdings",
      "category": "cyber-intel",
      "exchange": "NYSE",
      "price_gbp": "96",
      "price_usd": 129.24,
      "change_1d": "-3.62%",
      "change_1w": "+0.32%",
      "change_1m": "-8.85%",
      "change_ytd": "-28.90%",
      "return_1yr": "-28%",
      "low_gbp": "73",
      "low_usd": 98.86,
      "high_gbp": "153",
      "high_usd": 205.77,
      "bar_pct": 28,
      "market_cap_gbp_b": 12.032,
      "market_cap_usd_b": 16.219,
      "beta": 0.572,
      "pe_ratio": 12.4,
      "avg_volume_m": 1.61,
      "div_yield_pct": 129.0,
      "short_pct": 3.31,
      "analyst": "buy",
      "analyst_score": 2.35,
      "vol_1d": 1048700,
      "vol_1w": 5766300,
      "vol_1m": 23780000,
      "news": [
        {
          "title": "Can Growing ISR Demand Strengthen HII's Mission Technologies Business?",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/growing-isr-demand-strengthen-hiis-142500373.html",
          "published": 1789482300,
          "sentiment": 0.361
        },
        {
          "title": "Leidos Holdings Inc's Dividend Analysis",
          "publisher": "GuruFocus.com",
          "url": "https://finance.yahoo.com/markets/stocks/articles/leidos-holdings-incs-dividend-analysis-111009078.html",
          "published": 1789470609,
          "sentiment": 0.0
        },
        {
          "title": "Leidos Holdings (LDOS) Lands $875 Million Navy Network Extension For 650,000 Personnel",
          "publisher": "Simply Wall St.",
          "url": "https://finance.yahoo.com/markets/stocks/articles/leidos-holdings-ldos-lands-875-091052153.html",
          "published": 1789463452,
          "sentiment": 0.0
        },
        {
          "title": "2 Reasons to Watch LDOS and 1 to Stay Cautious",
          "publisher": "StockStory",
          "url": "https://finance.yahoo.com/markets/stocks/articles/2-reasons-watch-ldos-1-130730775.html",
          "published": 1789391250,
          "sentiment": -0.103
        },
        {
          "title": "Leidos (LDOS) Increases Despite Market Slip: Here's What You Need to Know",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/leidos-ldos-increases-despite-market-215005320.html",
          "published": 1789077005,
          "sentiment": 0.0
        }
      ],
      "news_sentiment": 0.052
    },
    {
      "ticker": "CACI",
      "company_name": "CACI International",
      "category": "cyber-intel",
      "exchange": "NYSE",
      "price_gbp": "472",
      "price_usd": 636.4,
      "change_1d": "-0.12%",
      "change_1w": "+1.77%",
      "change_1m": "-1.99%",
      "change_ytd": "+18.42%",
      "return_1yr": "+29%",
      "low_gbp": "322",
      "low_usd": 434.7,
      "high_gbp": "507",
      "high_usd": 683.5,
      "bar_pct": 81,
      "market_cap_gbp_b": 10.433,
      "market_cap_usd_b": 14.064,
      "beta": 0.571,
      "pe_ratio": 26.38,
      "avg_volume_m": 0.29,
      "div_yield_pct": null,
      "short_pct": 5.44,
      "analyst": "buy",
      "analyst_score": 1.56,
      "vol_1d": 252000,
      "vol_1w": 1406000,
      "vol_1m": 5245400,
      "news": [
        {
          "title": "Beat the Market the Zacks Way: FIGS, Microsoft, Amphenol in Focus",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/beat-market-zacks-way-figs-121100982.html",
          "published": 1789387860,
          "sentiment": 0.0
        },
        {
          "title": "Spotting Winners: CACI (NYSE:CACI) And Defense Contractors Stocks In Q2",
          "publisher": "StockStory",
          "url": "https://finance.yahoo.com/markets/stocks/articles/spotting-winners-caci-nyse-caci-220104267.html",
          "published": 1789077664,
          "sentiment": 0.557
        },
        {
          "title": "4 High-Growth GARP Stocks With Discounted PEG Ratios for 2026",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/4-high-growth-garp-stocks-190000359.html",
          "published": 1788548400,
          "sentiment": 0.052
        },
        {
          "title": "Why Is CACI International (CACI) Up 0.2% Since Last Earnings Report?",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/why-caci-international-caci-0-153036724.html",
          "published": 1788535836,
          "sentiment": 0.0
        },
        {
          "title": "Concerns Over Defense Spending Weighed on CACI International Inc (CACI)",
          "publisher": "Insider Monkey",
          "url": "https://finance.yahoo.com/markets/stocks/articles/concerns-over-defense-spending-weighed-143939144.html",
          "published": 1788532779,
          "sentiment": 0.128
        }
      ],
      "news_sentiment": 0.147
    },
    {
      "ticker": "SAIC",
      "company_name": "Science Applications International",
      "category": "cyber-intel",
      "exchange": "NYSE",
      "price_gbp": "99",
      "price_usd": 133.74,
      "change_1d": "+1.31%",
      "change_1w": "+4.85%",
      "change_1m": "+7.56%",
      "change_ytd": "+33.51%",
      "return_1yr": "+28%",
      "low_gbp": "60",
      "low_usd": 81.08,
      "high_gbp": "106",
      "high_usd": 142.66,
      "bar_pct": 86,
      "market_cap_gbp_b": 4.157,
      "market_cap_usd_b": 5.604,
      "beta": 0.297,
      "pe_ratio": 15.39,
      "avg_volume_m": 0.5,
      "div_yield_pct": 112.0,
      "short_pct": 6.46,
      "analyst": "hold",
      "analyst_score": 2.82,
      "vol_1d": 635700,
      "vol_1w": 2035600,
      "vol_1m": 10566300,
      "news": [
        {
          "title": "Government & Technical Consulting Stocks Q2 Earnings: SAIC (NASDAQ:SAIC) Best of the Bunch",
          "publisher": "StockStory",
          "url": "https://finance.yahoo.com/markets/stocks/articles/government-technical-consulting-stocks-q2-221038679.html",
          "published": 1788991838,
          "sentiment": 0.637
        },
        {
          "title": "Defense, Solar, and Refining Stocks Split as the Iran Conflict Raises Energy Risk",
          "publisher": "MarketBeat",
          "url": "https://www.marketbeat.com/articles/defense-solar-and-refining-stocks-split-as-the-iran-conflict-raises-energy-risk/?utm_source=yahoofinance&utm_medium=yahoofinance",
          "published": 1788959400,
          "sentiment": -0.202
        },
        {
          "title": "Stocks making big moves this week: SAIC, Reddit, Fortrea, GitLab, and G-III",
          "publisher": "StockStory",
          "url": "https://finance.yahoo.com/markets/stocks/articles/stocks-making-big-moves-week-203810253.html",
          "published": 1788554290,
          "sentiment": 0.0
        },
        {
          "title": "Science Applications (SAIC) Grew Revenue 6% but Posted a 0.6 Book-to-Bill Ratio. Is the $22B Backlog Enough?",
          "publisher": "Insider Monkey",
          "url": "https://finance.yahoo.com/markets/stocks/articles/science-applications-saic-grew-revenue-171604286.html",
          "published": 1788542151,
          "sentiment": 0.0
        },
        {
          "title": "1 Services Stock for Long-Term Investors and 2 We Avoid",
          "publisher": "StockStory",
          "url": "https://finance.yahoo.com/markets/stocks/articles/1-services-stock-long-term-122210320.html",
          "published": 1788524530,
          "sentiment": -0.296
        }
      ],
      "news_sentiment": 0.028
    },
    {
      "ticker": "BAH",
      "company_name": "Booz Allen Hamilton",
      "category": "cyber-intel",
      "exchange": "NYSE",
      "price_gbp": "59",
      "price_usd": 80.06,
      "change_1d": "+1.20%",
      "change_1w": "+11.02%",
      "change_1m": "+6.79%",
      "change_ytd": "-3.53%",
      "return_1yr": "-22%",
      "low_gbp": "44",
      "low_usd": 59.5,
      "high_gbp": "81",
      "high_usd": 109.1,
      "bar_pct": 41,
      "market_cap_gbp_b": 7.144,
      "market_cap_usd_b": 9.63,
      "beta": 0.365,
      "pe_ratio": 12.43,
      "avg_volume_m": 2.22,
      "div_yield_pct": 298.0,
      "short_pct": 6.99,
      "analyst": "hold",
      "analyst_score": 2.87,
      "vol_1d": 1865600,
      "vol_1w": 9541300,
      "vol_1m": 33689900,
      "news": [
        {
          "title": "Booz Allen Hamilton (BAH) Increases Despite Market Slip: Here's What You Need to Know",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/booz-allen-hamilton-bah-increases-221502912.html",
          "published": 1789510502,
          "sentiment": 0.0
        },
        {
          "title": "How Far Can Accenture Stock Move On You In Twelve Months?",
          "publisher": "Trefis",
          "url": "https://www.trefis.com/articles/615358/how-far-can-accenture-stock-move-on-you-in-twelve-months/2026-09-15",
          "published": 1789499340,
          "sentiment": 0.0
        },
        {
          "title": "What Is Booz Allen Hamilton Holding (BAH) Telling Investors With Its New AI Cyber Tools?",
          "publisher": "Simply Wall St.",
          "url": "https://finance.yahoo.com/technology/ai/articles/booz-allen-hamilton-holding-bah-151612131.html",
          "published": 1789485372,
          "sentiment": 0.0
        },
        {
          "title": "Sector Update: Tech Stocks Fall Late Afternoon",
          "publisher": "MT Newswires",
          "url": "https://finance.yahoo.com/technology/articles/sector-tech-stocks-fall-afternoon-200007387.html",
          "published": 1789416007,
          "sentiment": 0.0
        },
        {
          "title": "Palantir and Nvidia rethink AI use over a growing data risk",
          "publisher": "GuruFocus.com",
          "url": "https://finance.yahoo.com/news/palantir-nvidia-rethink-ai-over-190043439.html",
          "published": 1789412443,
          "sentiment": -0.103
        }
      ],
      "news_sentiment": -0.021
    },
    {
      "ticker": "AVAV",
      "company_name": "AeroVironment",
      "category": "drones",
      "exchange": "NASDAQ",
      "price_gbp": "116",
      "price_usd": 156.99,
      "change_1d": "+2.33%",
      "change_1w": "+5.52%",
      "change_1m": "-13.33%",
      "change_ytd": "-38.72%",
      "return_1yr": "-44%",
      "low_gbp": "100",
      "low_usd": 135.2,
      "high_gbp": "310",
      "high_usd": 417.86,
      "bar_pct": 8,
      "market_cap_gbp_b": 5.919,
      "market_cap_usd_b": 7.979,
      "beta": 1.406,
      "pe_ratio": null,
      "avg_volume_m": 1.94,
      "div_yield_pct": null,
      "short_pct": 11.21,
      "analyst": "buy",
      "analyst_score": 1.6,
      "vol_1d": 2501900,
      "vol_1w": 23942500,
      "vol_1m": 44916500,
      "news": [
        {
          "title": "AeroVironment (AVAV) Teams Up To Digitize Production And Test Data",
          "publisher": "Simply Wall St.",
          "url": "https://finance.yahoo.com/markets/stocks/articles/aerovironment-avav-teams-digitize-production-001740331.html",
          "published": 1789517860,
          "sentiment": 0.0
        },
        {
          "title": "Why investors are cheering this defense stock's space pivot",
          "publisher": "TheStreet",
          "url": "https://www.thestreet.com/investing/aerovironment-bluehalo-pentagon-space-contract",
          "published": 1789499580,
          "sentiment": 0.603
        },
        {
          "title": "A $100 Million Reason to Buy AVAV Stock",
          "publisher": "Barchart",
          "url": "https://www.barchart.com/story/news/4619396/a-100-million-reason-to-buy-avav-stock",
          "published": 1789498970,
          "sentiment": 0.0
        },
        {
          "title": "Swarmer Targets $200M in Pro Forma Revenue Next Year \u2013 Report",
          "publisher": "Exec Edge",
          "url": "https://finance.yahoo.com/markets/stocks/articles/swarmer-targets-200m-pro-forma-190125987.html",
          "published": 1789498885,
          "sentiment": 0.0
        },
        {
          "title": "Can DPRO Gain From the Shift Toward Secure, Domestic Drone Technology?",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/dpro-gain-shift-toward-secure-141700300.html",
          "published": 1789481820,
          "sentiment": 0.7
        }
      ],
      "news_sentiment": 0.261
    },
    {
      "ticker": "KTOS",
      "company_name": "Kratos Defense",
      "category": "drones",
      "exchange": "NASDAQ",
      "price_gbp": "35",
      "price_usd": 47.62,
      "change_1d": "-0.06%",
      "change_1w": "-1.20%",
      "change_1m": "-24.76%",
      "change_ytd": "-39.94%",
      "return_1yr": "-37%",
      "low_gbp": "32",
      "low_usd": 43.09,
      "high_gbp": "99",
      "high_usd": 134.0,
      "bar_pct": 5,
      "market_cap_gbp_b": 6.632,
      "market_cap_usd_b": 8.94,
      "beta": 1.113,
      "pe_ratio": 280.12,
      "avg_volume_m": 4.3,
      "div_yield_pct": null,
      "short_pct": 5.95,
      "analyst": "strong_buy",
      "analyst_score": 1.38,
      "vol_1d": 4283700,
      "vol_1w": 19507700,
      "vol_1m": 67561300,
      "news": [
        {
          "title": "This Stock Can Rise 150%, Plus 12 More Aerospace Buys",
          "publisher": "Barrons.com",
          "url": "https://www.barrons.com/articles/defense-stock-buys-guggenheim-northrop-grumman-8b568e43?siteid=yhoof2&yptr=yahoo",
          "published": 1789487820,
          "sentiment": 0.0
        },
        {
          "title": "Can ONDS' GATE & Bron Buyouts Fuel its Defense Growth Engine?",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/onds-gate-bron-buyouts-fuel-130300206.html",
          "published": 1789477380,
          "sentiment": 0.477
        },
        {
          "title": "How Could Project Anaconda Expand Kratos' Role in Naval Radar?",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/could-project-anaconda-expand-kratos-135700256.html",
          "published": 1789135020,
          "sentiment": 0.318
        },
        {
          "title": "Price Prediction: Rocket Lab\u2019s Next Leg Higher Could Be Massive, 95% Upside Ahead",
          "publisher": "24/7 Wall St.",
          "url": "https://247wallst.com/investing/2026/09/11/price-prediction-rocket-labs-next-leg-higher-could-be-massive-95-upside-ahead/",
          "published": 1789133442,
          "sentiment": 0.0
        },
        {
          "title": "ONDS Stock Sinks 22% YTD: Is it Time to Hold Tight or Head for Exit?",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/onds-stock-sinks-22-ytd-144500134.html",
          "published": 1788792300,
          "sentiment": 0.0
        }
      ],
      "news_sentiment": 0.159
    },
    {
      "ticker": "RCAT",
      "company_name": "Red Cat Holdings",
      "category": "drones",
      "exchange": "NASDAQ",
      "price_gbp": "5.91",
      "price_usd": 7.97,
      "change_1d": "+1.98%",
      "change_1w": "-8.40%",
      "change_1m": "-23.71%",
      "change_ytd": "-13.05%",
      "return_1yr": "-31%",
      "low_gbp": "4.28",
      "low_usd": 5.77,
      "high_gbp": "14",
      "high_usd": 18.78,
      "bar_pct": 17,
      "market_cap_gbp_b": 0.902,
      "market_cap_usd_b": 1.216,
      "beta": 1.355,
      "pe_ratio": null,
      "avg_volume_m": 8.83,
      "div_yield_pct": null,
      "short_pct": 23.07,
      "analyst": "strong_buy",
      "analyst_score": 1.38,
      "vol_1d": 6251000,
      "vol_1w": 29116800,
      "vol_1m": 131570300,
      "news": [
        {
          "title": "Swarmer Targets $200M in Pro Forma Revenue Next Year \u2013 Report",
          "publisher": "Exec Edge",
          "url": "https://finance.yahoo.com/markets/stocks/articles/swarmer-targets-200m-pro-forma-190125987.html",
          "published": 1789498885,
          "sentiment": 0.0
        },
        {
          "title": "Can DPRO Gain From the Shift Toward Secure, Domestic Drone Technology?",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/dpro-gain-shift-toward-secure-141700300.html",
          "published": 1789481820,
          "sentiment": 0.7
        },
        {
          "title": "AeroVironment Rises 6% as Post-Earnings Recovery Outpaces Drone Group; Ondas Ticks Up, Red Cat Barely Budges",
          "publisher": "24/7 Wall St.",
          "url": "https://247wallst.com/investing/2026/09/14/aerovironment-rises-6-as-post-earnings-recovery-outpaces-drone-group-ondas-ticks-up-red-cat-barely-budges/",
          "published": 1789405060,
          "sentiment": 0.0
        },
        {
          "title": "Ondas Raises 2026 Revenue View: Can It Deliver the Required H2 Ramp?",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/ondas-raises-2026-revenue-view-121800375.html",
          "published": 1789129080,
          "sentiment": 0.0
        },
        {
          "title": "Red Cat Holdings Director Sells 65,000 Shares for $552,500",
          "publisher": "Motley Fool",
          "url": "https://www.fool.com/coverage/filings/2026/09/09/red-cat-holdings-director-sells-65000-shares-for-552500/",
          "published": 1788987001,
          "sentiment": 0.296
        }
      ],
      "news_sentiment": 0.199
    },
    {
      "ticker": "TXT",
      "company_name": "Textron",
      "category": "drones",
      "exchange": "NYSE",
      "price_gbp": "60",
      "price_usd": 80.72,
      "change_1d": "+0.17%",
      "change_1w": "+1.51%",
      "change_1m": "-7.88%",
      "change_ytd": "-7.21%",
      "return_1yr": "-3%",
      "low_gbp": "58",
      "low_usd": 78.12,
      "high_gbp": "75",
      "high_usd": 101.57,
      "bar_pct": 11,
      "market_cap_gbp_b": 10.299,
      "market_cap_usd_b": 13.883,
      "beta": 0.898,
      "pe_ratio": 15.17,
      "avg_volume_m": 1.69,
      "div_yield_pct": 10.0,
      "short_pct": 5.1,
      "analyst": "buy",
      "analyst_score": 2.19,
      "vol_1d": 1533500,
      "vol_1w": 10680900,
      "vol_1m": 34293100,
      "news": [
        {
          "title": "Solid Demand in Commercial Aerospace Drives Howmet: Can It Sustain?",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/solid-demand-commercial-aerospace-drives-152900894.html",
          "published": 1789140540,
          "sentiment": 0.026
        },
        {
          "title": "Strong Orders Drive GE's Defense & Propulsion: Can Momentum Sustain?",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/strong-orders-drive-ges-defense-161900768.html",
          "published": 1789057140,
          "sentiment": 0.586
        },
        {
          "title": "Textron (TXT) Names A New Aviation Chief, Is The 23% Discount Warranted?",
          "publisher": "Simply Wall St.",
          "url": "https://finance.yahoo.com/markets/stocks/articles/textron-txt-names-aviation-chief-111157771.html",
          "published": 1788520317,
          "sentiment": 0.0
        },
        {
          "title": "Textron (TXT): Buy, Sell, or Hold Post Q2 Earnings?",
          "publisher": "StockStory",
          "url": "https://finance.yahoo.com/markets/stocks/articles/textron-txt-buy-sell-hold-171118458.html",
          "published": 1788455478,
          "sentiment": 0.0
        },
        {
          "title": "Howmet's Transportation Market Under Pressure: Is the Risk Priced In?",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/howmets-transportation-market-under-pressure-152800724.html",
          "published": 1788449280,
          "sentiment": -0.511
        }
      ],
      "news_sentiment": 0.02
    },
    {
      "ticker": "SPCX",
      "company_name": "SpaceX",
      "category": "space",
      "exchange": "NASDAQ",
      "price_gbp": "106",
      "price_usd": 143.49,
      "change_1d": "-3.46%",
      "change_1w": "-6.50%",
      "change_1m": "-1.87%",
      "change_ytd": "-10.85%",
      "return_1yr": "-8%",
      "low_gbp": "78",
      "low_usd": 104.83,
      "high_gbp": "167",
      "high_usd": 225.64,
      "bar_pct": 32,
      "market_cap_gbp_b": 1403.156,
      "market_cap_usd_b": 1891.454,
      "beta": null,
      "pe_ratio": null,
      "avg_volume_m": 97.95,
      "div_yield_pct": null,
      "short_pct": 2.76,
      "analyst": "buy",
      "analyst_score": 1.67,
      "vol_1d": 72432600,
      "vol_1w": 458759400,
      "vol_1m": 1643037000,
      "news": [
        {
          "title": "Bessent defends Trump administration's safety stance on AI",
          "publisher": "Yahoo Finance",
          "url": "https://finance.yahoo.com/technology/ai/article/bessent-defends-trump-administrations-safety-stance-on-ai-201653080.html",
          "published": 1789503413,
          "sentiment": 0.421
        },
        {
          "title": "Musk hints (again) at possible SpaceX, Tesla merger",
          "publisher": "Yahoo Finance",
          "url": "https://finance.yahoo.com/markets/stocks/article/musk-hints-again-at-possible-spacex-tesla-merger-135029754.html",
          "published": 1789480229,
          "sentiment": 0.0
        },
        {
          "title": "SpaceX just won something that gives its investors hope",
          "publisher": "TheStreet",
          "url": "https://www.thestreet.com/investing/stocks/spacex-won-ai-hosting-deal-giving-investors-hope",
          "published": 1789529580,
          "sentiment": 0.765
        },
        {
          "title": "Elon Musk Could Fund Every $1,000 'Trump Account' Through 2028 and Still Be Worth Over $900 Billion",
          "publisher": "Benzinga",
          "url": "https://finance.yahoo.com/markets/stocks/articles/elon-musk-could-fund-every-033037704.html",
          "published": 1789529437,
          "sentiment": 0.226
        },
        {
          "title": "RKLB, ASTS, SPCX, RDW Stocks Set For A Boost? Pentagon Confirms Orbital Weapons Use, Ramps Up Golden Dome Plans",
          "publisher": "Stocktwits",
          "url": "https://stocktwits.com/news-articles/markets/equity/rklb-asts-spcx-rdw-stocks-pentagon-orbital-weapons-golden-dome-plans/cZtYcxMRB2P",
          "published": 1789528674,
          "sentiment": -0.052
        }
      ],
      "news_sentiment": 0.272
    },
    {
      "ticker": "RKLB",
      "company_name": "Rocket Lab USA",
      "category": "space",
      "exchange": "NASDAQ",
      "price_gbp": "47",
      "price_usd": 63.55,
      "change_1d": "+1.60%",
      "change_1w": "-3.52%",
      "change_1m": "-22.58%",
      "change_ytd": "-16.37%",
      "return_1yr": "+30%",
      "low_gbp": "28",
      "low_usd": 37.57,
      "high_gbp": "112",
      "high_usd": 151.0,
      "bar_pct": 23,
      "market_cap_gbp_b": 30.144,
      "market_cap_usd_b": 40.634,
      "beta": 2.612,
      "pe_ratio": null,
      "avg_volume_m": 20.9,
      "div_yield_pct": null,
      "short_pct": 7.63,
      "analyst": "buy",
      "analyst_score": 1.6,
      "vol_1d": 20394200,
      "vol_1w": 95669900,
      "vol_1m": 350215100,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "PL",
      "company_name": "Planet Labs",
      "category": "space",
      "exchange": "NYSE",
      "price_gbp": "12",
      "price_usd": 16.02,
      "change_1d": "-1.29%",
      "change_1w": "-10.05%",
      "change_1m": "-34.29%",
      "change_ytd": "-21.51%",
      "return_1yr": "+58%",
      "low_gbp": "7.18",
      "low_usd": 9.68,
      "high_gbp": "38",
      "high_usd": 51.76,
      "bar_pct": 15,
      "market_cap_gbp_b": 4.324,
      "market_cap_usd_b": 5.829,
      "beta": 2.108,
      "pe_ratio": null,
      "avg_volume_m": 9.7,
      "div_yield_pct": null,
      "short_pct": 9.67,
      "analyst": "buy",
      "analyst_score": 1.75,
      "vol_1d": 8375300,
      "vol_1w": 52508100,
      "vol_1m": 211483000,
      "news": [
        {
          "title": "Spotting Winners: Planet Labs (NYSE:PL) And Data & Business Process Services Stocks In Q2",
          "publisher": "StockStory",
          "url": "https://finance.yahoo.com/markets/stocks/articles/spotting-winners-planet-labs-nyse-220330732.html",
          "published": 1789423410,
          "sentiment": 0.477
        },
        {
          "title": "Planet Labs' 2026 Outlook: Government Contracts Power Revenue Growth",
          "publisher": "Motley Fool",
          "url": "https://www.fool.com/coverage/moneyball/2026/09/13/planet-labs-2026-outlook-government-contracts-power-revenue-growth/",
          "published": 1789342554,
          "sentiment": 0.382
        },
        {
          "title": "Planet Labs Has Fallen Back to Earth, But Wall Street Still Sees a Rebound",
          "publisher": "MarketBeat",
          "url": "https://www.marketbeat.com/articles/planet-labs-has-fallen-back-to-earth-but-wall-street-still-sees-a-rebound/?utm_source=yahoofinance&utm_medium=yahoofinance",
          "published": 1789308900,
          "sentiment": -0.19
        },
        {
          "title": "RKLB Stock: What's Behind The 39% Drop?",
          "publisher": "Trefis",
          "url": "https://www.trefis.com/articles/615056/rklb-stock-whats-behind-the-39-drop/2026-09-11",
          "published": 1789148486,
          "sentiment": -0.273
        },
        {
          "title": "Planet Labs PBC (PL) Upgraded to Buy: Here's What You Should Know",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/planet-labs-pbc-pl-upgraded-160002125.html",
          "published": 1789056002,
          "sentiment": 0.0
        }
      ],
      "news_sentiment": 0.079
    },
    {
      "ticker": "ASTS",
      "company_name": "AST SpaceMobile",
      "category": "space",
      "exchange": "NASDAQ",
      "price_gbp": "44",
      "price_usd": 58.77,
      "change_1d": "-2.05%",
      "change_1w": "-11.12%",
      "change_1m": "-17.39%",
      "change_ytd": "-29.59%",
      "return_1yr": "+46%",
      "low_gbp": "29",
      "low_usd": 39.5,
      "high_gbp": "99",
      "high_usd": 133.86,
      "bar_pct": 20,
      "market_cap_gbp_b": 16.967,
      "market_cap_usd_b": 22.872,
      "beta": 2.726,
      "pe_ratio": null,
      "avg_volume_m": 14.58,
      "div_yield_pct": null,
      "short_pct": 21.46,
      "analyst": "hold",
      "analyst_score": 2.57,
      "vol_1d": 7181300,
      "vol_1w": 37382500,
      "vol_1m": 195145800,
      "news": [
        {
          "title": "RKLB, ASTS, SPCX, RDW Stocks Set For A Boost? Pentagon Confirms Orbital Weapons Use, Ramps Up Golden Dome Plans",
          "publisher": "Stocktwits",
          "url": "https://stocktwits.com/news-articles/markets/equity/rklb-asts-spcx-rdw-stocks-pentagon-orbital-weapons-golden-dome-plans/cZtYcxMRB2P",
          "published": 1789528674,
          "sentiment": -0.052
        },
        {
          "title": "AST SpaceMobile, Inc. (ASTS) Declines More Than Market: Some Information for Investors",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/ast-spacemobile-inc-asts-declines-220004358.html",
          "published": 1789509604,
          "sentiment": 0.0
        },
        {
          "title": "AST SpaceMobile vs. Redwire: Which Space Infrastructure Stock Is a Better Buy in 2026?",
          "publisher": "Motley Fool",
          "url": "https://www.fool.com/coverage/better-buy/2026/09/15/ast-spacemobile-vs-redwire-which-space-infrastructure-stock-is-a-better-buy-in-2026/",
          "published": 1789502941,
          "sentiment": 0.44
        },
        {
          "title": "The Space Race Is Heating Up \u2014 and One Analyst Says Buy These 2 Stocks",
          "publisher": "TipRanks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/space-race-heating-one-analyst-180500708.html",
          "published": 1789495500,
          "sentiment": 0.0
        },
        {
          "title": "Rocket Lab Rises 3% on Iridium Deal Optimism; SpaceX and AST SpaceMobile Slip 1%",
          "publisher": "24/7 Wall St.",
          "url": "https://247wallst.com/investing/2026/09/15/rocket-lab-rises-3-on-iridium-deal-optimism-spacex-and-ast-spacemobile-slip-1/",
          "published": 1789481197,
          "sentiment": 0.542
        }
      ],
      "news_sentiment": 0.186
    },
    {
      "ticker": "TDG",
      "company_name": "TransDigm Group",
      "category": "weapons",
      "exchange": "NYSE",
      "price_gbp": "805",
      "price_usd": 1085.0,
      "change_1d": "-2.36%",
      "change_1w": "-5.25%",
      "change_1m": "-12.35%",
      "change_ytd": "-20.14%",
      "return_1yr": "-13%",
      "low_gbp": "803",
      "low_usd": 1082.4,
      "high_gbp": "1085",
      "high_usd": 1463.03,
      "bar_pct": 1,
      "market_cap_gbp_b": 44.492,
      "market_cap_usd_b": 59.975,
      "beta": 0.893,
      "pe_ratio": 33.67,
      "avg_volume_m": 0.4,
      "div_yield_pct": null,
      "short_pct": 2.17,
      "analyst": "buy",
      "analyst_score": 2.09,
      "vol_1d": 439000,
      "vol_1w": 1945200,
      "vol_1m": 7298300,
      "news": [
        {
          "title": "Why Today\u2019s GE Downgrade Wasn\u2019t Just a Downgrade",
          "publisher": "Barrons.com",
          "url": "https://www.barrons.com/articles/ge-stock-downgrade-06e25a0c?siteid=yhoof2&yptr=yahoo",
          "published": 1789414200,
          "sentiment": 0.0
        },
        {
          "title": "Nike downgraded, Affirm upgraded: Wall Street's top analyst calls",
          "publisher": "The Fly",
          "url": "https://finance.yahoo.com/markets/stocks/articles/nike-downgraded-affirm-upgraded-wall-134559486.html",
          "published": 1789393559,
          "sentiment": 0.202
        },
        {
          "title": "These 5 Aviation Stocks Slide As Melius Warns \u2018Several Years Of Robust\u2019 Aftermarket Growth May Be Ending",
          "publisher": "Stocktwits",
          "url": "https://stocktwits.com/news-articles/markets/equity/5-aviation-stocks-slide-melius-warns-years-of-robust-aftermarket-growth-ending/cZtmcbvRBRF",
          "published": 1789388243,
          "sentiment": 0.296
        },
        {
          "title": "Should You Buy Howmet Stock After Its Turbine Blade Scare?",
          "publisher": "Trefis",
          "url": "https://www.trefis.com/articles/614708/should-you-buy-howmet-stock-after-its-turbine-blade-scare/2026-09-09",
          "published": 1789005470,
          "sentiment": -0.494
        },
        {
          "title": "GE Aerospace Strikes $11.75 Billion Deal to Buy Consolidated Precision Products",
          "publisher": "MT Newswires",
          "url": "https://finance.yahoo.com/markets/stocks/articles/ge-aerospace-strikes-11-75-155648702.html",
          "published": 1788883008,
          "sentiment": -0.361
        }
      ],
      "news_sentiment": -0.071
    },
    {
      "ticker": "HEI",
      "company_name": "HEICO Corporation",
      "category": "weapons",
      "exchange": "NYSE",
      "price_gbp": "220",
      "price_usd": 296.85,
      "change_1d": "-2.27%",
      "change_1w": "-6.09%",
      "change_1m": "-20.05%",
      "change_ytd": "-9.79%",
      "return_1yr": "-4%",
      "low_gbp": "190",
      "low_usd": 256.11,
      "high_gbp": "280",
      "high_usd": 376.86,
      "bar_pct": 34,
      "market_cap_gbp_b": 30.777,
      "market_cap_usd_b": 41.487,
      "beta": 1.038,
      "pe_ratio": 50.48,
      "avg_volume_m": 0.47,
      "div_yield_pct": 8.0,
      "short_pct": 1.39,
      "analyst": "buy",
      "analyst_score": 1.96,
      "vol_1d": 464200,
      "vol_1w": 2297900,
      "vol_1m": 10908700,
      "news": [
        {
          "title": "Why Today\u2019s GE Downgrade Wasn\u2019t Just a Downgrade",
          "publisher": "Barrons.com",
          "url": "https://www.barrons.com/articles/ge-stock-downgrade-06e25a0c?siteid=yhoof2&yptr=yahoo",
          "published": 1789414200,
          "sentiment": 0.0
        },
        {
          "title": "Nike downgraded, Affirm upgraded: Wall Street's top analyst calls",
          "publisher": "The Fly",
          "url": "https://finance.yahoo.com/markets/stocks/articles/nike-downgraded-affirm-upgraded-wall-134559486.html",
          "published": 1789393559,
          "sentiment": 0.202
        },
        {
          "title": "These 5 Aviation Stocks Slide As Melius Warns \u2018Several Years Of Robust\u2019 Aftermarket Growth May Be Ending",
          "publisher": "Stocktwits",
          "url": "https://stocktwits.com/news-articles/markets/equity/5-aviation-stocks-slide-melius-warns-years-of-robust-aftermarket-growth-ending/cZtmcbvRBRF",
          "published": 1789388243,
          "sentiment": 0.296
        },
        {
          "title": "Heico (HEI.A) Loses 10.0% in 4 Weeks, Here's Why a Trend Reversal May be Around the Corner",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/heico-hei-loses-10-0-133502119.html",
          "published": 1788442502,
          "sentiment": -0.318
        },
        {
          "title": "2 of Wall Street\u2019s Favorite Stocks with Impressive Fundamentals and 1 We Avoid",
          "publisher": "StockStory",
          "url": "https://finance.yahoo.com/markets/stocks/articles/2-wall-street-favorite-stocks-111118103.html",
          "published": 1788433878,
          "sentiment": 0.625
        }
      ],
      "news_sentiment": 0.161
    },
    {
      "ticker": "AXON",
      "company_name": "Axon Enterprise",
      "category": "weapons",
      "exchange": "NASDAQ",
      "price_gbp": "328",
      "price_usd": 442.08,
      "change_1d": "-10.24%",
      "change_1w": "-12.53%",
      "change_1m": "-26.85%",
      "change_ytd": "-21.54%",
      "return_1yr": "-35%",
      "low_gbp": "251",
      "low_usd": 339.01,
      "high_gbp": "588",
      "high_usd": 792.16,
      "bar_pct": 23,
      "market_cap_gbp_b": 26.642,
      "market_cap_usd_b": 35.913,
      "beta": 1.399,
      "pe_ratio": 203.72,
      "avg_volume_m": 0.95,
      "div_yield_pct": null,
      "short_pct": 5.28,
      "analyst": "buy",
      "analyst_score": 1.67,
      "vol_1d": 2778400,
      "vol_1w": 5652500,
      "vol_1m": 17654900,
      "news": [
        {
          "title": "Axon Enterprise (AXON) Dips More Than Broader Market: What You Should Know",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/axon-enterprise-axon-dips-more-220005906.html",
          "published": 1789509605,
          "sentiment": 0.0
        },
        {
          "title": "Why Axon (AXON) Stock Is Trading Lower Today",
          "publisher": "StockStory",
          "url": "https://finance.yahoo.com/markets/stocks/articles/why-axon-axon-stock-trading-215931986.html",
          "published": 1789509571,
          "sentiment": -0.296
        },
        {
          "title": "Why Rule Breakers Dig Stocks With Multiple Futures",
          "publisher": "Motley Fool",
          "url": "https://www.fool.com/investing/2026/09/15/why-rule-breakers-dig-stocks-with-multiple-futures/",
          "published": 1789509241,
          "sentiment": 0.0
        },
        {
          "title": "US Equity Markets End Lower as 10-Year Treasury Yield Climbs to Highest Since 2007, Oil Jumps",
          "publisher": "MT Newswires",
          "url": "https://finance.yahoo.com/markets/stocks/articles/us-equity-markets-end-lower-204246538.html",
          "published": 1789504966,
          "sentiment": -0.103
        },
        {
          "title": "Update: Equities Log Back-to-Back Declines Before Fed Decision as Yields, Oil Jump",
          "publisher": "MT Newswires",
          "url": "https://finance.yahoo.com/markets/stocks/articles/equities-log-back-back-declines-203714855.html",
          "published": 1789504634,
          "sentiment": 0.0
        }
      ],
      "news_sentiment": -0.08
    },
    {
      "ticker": "OLN",
      "company_name": "Olin Corporation",
      "category": "weapons",
      "exchange": "NYSE",
      "price_gbp": "13",
      "price_usd": 17.14,
      "change_1d": "+1.54%",
      "change_1w": "-4.19%",
      "change_1m": "-8.80%",
      "change_ytd": "-18.33%",
      "return_1yr": "-33%",
      "low_gbp": "12",
      "low_usd": 16.68,
      "high_gbp": "23",
      "high_usd": 30.46,
      "bar_pct": 3,
      "market_cap_gbp_b": 1.449,
      "market_cap_usd_b": 1.953,
      "beta": 1.193,
      "pe_ratio": null,
      "avg_volume_m": 3.2,
      "div_yield_pct": 474.0,
      "short_pct": 11.76,
      "analyst": "hold",
      "analyst_score": 2.86,
      "vol_1d": 3001200,
      "vol_1w": 11780300,
      "vol_1m": 55912600,
      "news": [
        {
          "title": "Olin, Huntsman Merger of Equals Clears U.S. Antitrust Hurdle",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/olin-huntsman-merger-equals-clears-140200690.html",
          "published": 1789394520,
          "sentiment": 0.077
        },
        {
          "title": "Here's Why You Should Retain Olin Stock in Your Portfolio",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/heres-why-retain-olin-stock-120700050.html",
          "published": 1788264420,
          "sentiment": 0.0
        },
        {
          "title": "Huntsman Stockholders Approve Olin Merger Agreement at Special Meeting",
          "publisher": "MarketBeat",
          "url": "https://www.marketbeat.com/instant-alerts/event-huntsman-stockholders-approve-olin-merger-agreement-at-special-meeting-2026-08-27/?utm_source=yahoofinance&utm_medium=yahoofinance",
          "published": 1787814113,
          "sentiment": 0.71
        },
        {
          "title": "OLN-HUN's All-Stock Merger of Equals Approved by Shareholders",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/oln-huns-stock-merger-equals-161700325.html",
          "published": 1787761020,
          "sentiment": 0.421
        },
        {
          "title": "AVNT Q2 Earnings Top Estimates on Organic Growth, Guidance Up",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/avnt-q2-earnings-top-estimates-142800811.html",
          "published": 1786631280,
          "sentiment": 0.527
        }
      ],
      "news_sentiment": 0.347
    },
    {
      "ticker": "MRCY",
      "company_name": "Mercury Systems",
      "category": "weapons",
      "exchange": "NASDAQ",
      "price_gbp": "65",
      "price_usd": 87.01,
      "change_1d": "+7.38%",
      "change_1w": "+4.25%",
      "change_1m": "-23.24%",
      "change_ytd": "+14.44%",
      "return_1yr": "+10%",
      "low_gbp": "48",
      "low_usd": 65.04,
      "high_gbp": "95",
      "high_usd": 128.45,
      "bar_pct": 35,
      "market_cap_gbp_b": 3.882,
      "market_cap_usd_b": 5.233,
      "beta": 0.98,
      "pe_ratio": null,
      "avg_volume_m": 0.75,
      "div_yield_pct": null,
      "short_pct": 10.09,
      "analyst": "buy",
      "analyst_score": 1.91,
      "vol_1d": 1075000,
      "vol_1w": 3422300,
      "vol_1m": 18968600,
      "news": [
        {
          "title": "1 Cash-Producing Stock for Long-Term Investors and 2 We Question",
          "publisher": "StockStory",
          "url": "https://finance.yahoo.com/markets/stocks/articles/1-cash-producing-stock-long-234705312.html",
          "published": 1789170425,
          "sentiment": 0.0
        },
        {
          "title": "3 of Wall Street\u2019s Favorite Stocks We Think Twice About",
          "publisher": "StockStory",
          "url": "https://finance.yahoo.com/markets/stocks/articles/3-wall-street-favorite-stocks-130318200.html",
          "published": 1788440598,
          "sentiment": 0.459
        },
        {
          "title": "Mercury Systems (MRCY) Slides As Valuation Views Split, Is The Stock 22% Undervalued?",
          "publisher": "Simply Wall St.",
          "url": "https://finance.yahoo.com/markets/stocks/articles/mercury-systems-mrcy-slides-valuation-032731617.html",
          "published": 1788406051,
          "sentiment": 0.0
        },
        {
          "title": "Insider Waves Goodbye to More Than 48,000 Shares of Defense Stock Worth $4.8 Million",
          "publisher": "Motley Fool",
          "url": "https://www.fool.com/coverage/filings/2026/09/02/insider-waves-goodbye-to-more-than-48-000-shares-of-defense-stock-worth-usd4-8-million/",
          "published": 1788363301,
          "sentiment": 0.595
        },
        {
          "title": "Mercury Systems (MRCY) Is Sitting On A Record Pile Of Orders",
          "publisher": "Insider Monkey",
          "url": "https://finance.yahoo.com/markets/stocks/articles/mercury-systems-mrcy-sitting-record-094015155.html",
          "published": 1787823615,
          "sentiment": 0.0
        }
      ],
      "news_sentiment": 0.211
    },
    {
      "ticker": "DRS",
      "company_name": "Leonardo DRS",
      "category": "weapons",
      "exchange": "NYSE",
      "price_gbp": "27",
      "price_usd": 36.88,
      "change_1d": "+1.23%",
      "change_1w": "-0.16%",
      "change_1m": "-18.68%",
      "change_ytd": "+6.68%",
      "return_1yr": "-14%",
      "low_gbp": "24",
      "low_usd": 32.43,
      "high_gbp": "38",
      "high_usd": 50.59,
      "bar_pct": 25,
      "market_cap_gbp_b": 7.301,
      "market_cap_usd_b": 9.842,
      "beta": 0.138,
      "pe_ratio": 30.23,
      "avg_volume_m": 0.97,
      "div_yield_pct": 100.0,
      "short_pct": 1.17,
      "analyst": "strong_buy",
      "analyst_score": 1.45,
      "vol_1d": 1293000,
      "vol_1w": 4037200,
      "vol_1m": 17428500,
      "news": [
        {
          "title": "Q2 Earnings Highs And Lows: Leonardo DRS (NASDAQ:DRS) Vs The Rest Of The Defense Contractors Stocks",
          "publisher": "StockStory",
          "url": "https://finance.yahoo.com/markets/stocks/articles/q2-earnings-highs-lows-leonardo-235918110.html",
          "published": 1788479958,
          "sentiment": -0.077
        },
        {
          "title": "Rocket Lab Surges 43.7% in a Year: Is There More Room to Run?",
          "publisher": "Zacks",
          "url": "https://finance.yahoo.com/markets/stocks/articles/rocket-lab-surges-43-7-135700002.html",
          "published": 1788357420,
          "sentiment": 0.0
        },
        {
          "title": "1 Industrials Stock for Long-Term Investors and 2 We Avoid",
          "publisher": "StockStory",
          "url": "https://finance.yahoo.com/markets/stocks/articles/1-industrials-stock-long-term-103252746.html",
          "published": 1787913172,
          "sentiment": -0.296
        },
        {
          "title": "1 of Wall Street\u2019s Favorite Stocks to Keep an Eye On and 2 We Turn Down",
          "publisher": "StockStory",
          "url": "https://finance.yahoo.com/markets/stocks/articles/1-wall-street-favorite-stocks-154507067.html",
          "published": 1787845507,
          "sentiment": 0.459
        },
        {
          "title": "Leonardo DRS (DRS) Stock Looks Fully Valued Even After Recent Weakness",
          "publisher": "Simply Wall St.",
          "url": "https://finance.yahoo.com/markets/stocks/articles/leonardo-drs-drs-stock-looks-110711351.html",
          "published": 1787742431,
          "sentiment": 0.101
        }
      ],
      "news_sentiment": 0.037
    }
  ]
};
