version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/AI"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/Biotech"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/Defence"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/Tech"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/Crypto"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/Energy"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/MegaCap"
    schedule:
      interval: "weekly"
