window.PRICES_DATA = {
  "updated": "2026-07-30 22:46",
  "fx_gbp_usd": 1.3464,
  "stocks": [
    {
      "ticker": "BTC",
      "yf_ticker": "BTC-USD",
      "company_name": "Bitcoin",
      "category": "bitcoin",
      "exchange": "Crypto",
      "price_gbp": "48059",
      "price_usd": 64707.852585,
      "change_1d": "+1.83%",
      "change_1w": "-0.52%",
      "change_1m": "+10.53%",
      "change_ytd": "-26.07%",
      "return_1yr": "-26%",
      "low_gbp": "43498",
      "low_usd": 58566.091992,
      "high_gbp": "92646",
      "high_usd": 124739.810888,
      "bar_pct": 9,
      "market_cap_gbp_b": 964.232,
      "market_cap_usd_b": 1298.262,
      "avg_volume_m": 22877.33,
      "cmc_rank": 1,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 28201903974,
      "vol_1w": 160141294188,
      "vol_1m": 792814536470,
      "news": [
        {
          "title": "US stocks, bitcoin gain since Fed held rates steady at July FOMC meeting",
          "publisher": "Yahoo Finance Video",
          "url": "https://finance.yahoo.com/video/us-stocks-bitcoin-gain-since-162000444.html",
          "published": 1785428400,
          "sentiment": 0.527
        },
        {
          "title": "Strategy Stock Is Under Pressure. Earnings Show Management Has a New Playbook.",
          "publisher": "Barrons.com",
          "url": "https://www.barrons.com/articles/strategy-earnings-stock-price-ff30d6f8?siteid=yhoof2&yptr=yahoo",
          "published": 1785445080,
          "sentiment": -0.296
        },
        {
          "title": "Coinbase Revenue Miss Sends COIN Stock Lower Despite Record Market Share",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/coinbase-revenue-coin-stock/",
          "published": 1785445004,
          "sentiment": -0.57
        },
        {
          "title": "Strategy shares edge lower after bitcoin losses drive Q2 miss",
          "publisher": "Investing.com",
          "url": "https://finance.yahoo.com/markets/crypto/articles/strategy-shares-edge-lower-bitcoin-205423508.html",
          "published": 1785444863,
          "sentiment": -0.511
        },
        {
          "title": "Coinbase Misses on Earnings Amid Moribund Crypto Market. The Stock Is Falling.",
          "publisher": "Barrons.com",
          "url": "https://www.barrons.com/articles/coinbase-earnings-stock-price-32ce7c46?siteid=yhoof2&yptr=yahoo",
          "published": 1785444360,
          "sentiment": -0.361
        }
      ],
      "news_sentiment": -0.242
    },
    {
      "ticker": "ETH",
      "yf_ticker": "ETH-USD",
      "company_name": "Ethereum",
      "category": "layer1",
      "exchange": "Crypto",
      "price_gbp": "1427",
      "price_usd": 1921.150602,
      "change_1d": "+1.70%",
      "change_1w": "+2.17%",
      "change_1m": "+22.41%",
      "change_ytd": "-35.24%",
      "return_1yr": "-35%",
      "low_gbp": "1163",
      "low_usd": 1566.00813,
      "high_gbp": "3578",
      "high_usd": 4817.762322,
      "bar_pct": 11,
      "market_cap_gbp_b": 172.197,
      "market_cap_usd_b": 231.849,
      "avg_volume_m": 8675.69,
      "cmc_rank": 2,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 10381004662,
      "vol_1w": 60729838411,
      "vol_1m": 294108086859,
      "news": [
        {
          "title": "Microsoft and Meta boost AI spending, but only one stock pays the price",
          "publisher": "Yahoo Finance Video",
          "url": "https://finance.yahoo.com/video/microsoft-meta-boost-ai-spending-160000943.html",
          "published": 1785427200,
          "sentiment": 0.214
        },
        {
          "title": "Bitcoin and ethereum prices today, Thursday, July 30, 2026: Prices rise after Fed leaves rates unchanged",
          "publisher": "Yahoo Personal Finance",
          "url": "https://finance.yahoo.com/personal-finance/investing/article/bitcoin-and-ethereum-prices-today-thursday-july-30-2026-prices-rise-after-fed-leaves-rates-unchanged-132340233.html",
          "published": 1785417820,
          "sentiment": 0.0
        },
        {
          "title": "This underrated token beats Bitcoin and Ethereum with 50% weekly gains",
          "publisher": "TheStreet",
          "url": "https://www.thestreet.com/crypto/markets/forget-bitcoin-ethereum-this-underrated-token-is-beating-everyone-after-posting-50-weekly-gains",
          "published": 1785434404,
          "sentiment": 0.34
        },
        {
          "title": "A New Crypto Index Just Launched. Here's Why That's Bullish for Ethereum, Solana, and Hyperliquid.",
          "publisher": "Motley Fool",
          "url": "https://www.fool.com/investing/2026/07/30/a-new-crypto-index-just-launched-heres-why-thats-b/",
          "published": 1785430200,
          "sentiment": 0.128
        },
        {
          "title": "Cathie Wood's Ark Invest Sells Bitmine While Adding to Coinbase and Circle Holdings",
          "publisher": "decrypt",
          "url": "https://decrypt.co/374738/cathie-wood-ark-invest-sells-bitmine-adds-coinbase-circle",
          "published": 1785429326,
          "sentiment": 0.0
        }
      ],
      "news_sentiment": 0.136
    },
    {
      "ticker": "SOL",
      "yf_ticker": "SOL-USD",
      "company_name": "Solana",
      "category": "layer1",
      "exchange": "Crypto",
      "price_gbp": "55",
      "price_usd": 74.423245,
      "change_1d": "+1.98%",
      "change_1w": "-2.07%",
      "change_1m": "+1.51%",
      "change_ytd": "-40.23%",
      "return_1yr": "-40%",
      "low_gbp": "46",
      "low_usd": 62.179183,
      "high_gbp": "184",
      "high_usd": 247.599444,
      "bar_pct": 7,
      "market_cap_gbp_b": 32.037,
      "market_cap_usd_b": 43.135,
      "avg_volume_m": 1490.43,
      "cmc_rank": 7,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 1773230985,
      "vol_1w": 10433044110,
      "vol_1m": 56383485486,
      "news": [
        {
          "title": "RWA Trend Takes a Jurassic Turn as First Tokenized Dinosaur Lands on Solana",
          "publisher": "CCN",
          "url": "https://www.ccn.com/news/crypto/rwa-trend-takes-a-jurassic-turn-as-first-tokenized-dinosaur-lands-on-solana/",
          "published": 1785444133,
          "sentiment": 0.0
        },
        {
          "title": "A New Crypto Index Just Launched. Here's Why That's Bullish for Ethereum, Solana, and Hyperliquid.",
          "publisher": "Motley Fool",
          "url": "https://www.fool.com/investing/2026/07/30/a-new-crypto-index-just-launched-heres-why-thats-b/",
          "published": 1785430200,
          "sentiment": 0.128
        },
        {
          "title": "Crypto Exchange Luno Cuts 20% Of Staff",
          "publisher": "CryptoProwl",
          "url": "https://www.cryptoprowl.com/releases/crypto-exchange-luno-cuts-20-of-staff-6293",
          "published": 1785362760,
          "sentiment": -0.296
        },
        {
          "title": "Top Cryptocurrencies Mixed; Bitcoin Holds Above $63,000",
          "publisher": "MT Newswires",
          "url": "https://finance.yahoo.com/markets/crypto/articles/top-cryptocurrencies-mixed-bitcoin-holds-195600234.html",
          "published": 1785354960,
          "sentiment": 0.202
        },
        {
          "title": "Morgan Stanley offering new ethereum, solana ETFs",
          "publisher": "Yahoo Finance Video",
          "url": "https://finance.yahoo.com/video/morgan-stanley-offering-ethereum-solana-193000936.html",
          "published": 1785353400,
          "sentiment": 0.0
        }
      ],
      "news_sentiment": 0.007
    },
    {
      "ticker": "BNB",
      "yf_ticker": "BNB-USD",
      "company_name": "BNB",
      "category": "layer1",
      "exchange": "Crypto",
      "price_gbp": "439",
      "price_usd": 591.204566,
      "change_1d": "+4.20%",
      "change_1w": "+4.33%",
      "change_1m": "+8.65%",
      "change_ytd": "-31.51%",
      "return_1yr": "-32%",
      "low_gbp": "405",
      "low_usd": 545.864131,
      "high_gbp": "971",
      "high_usd": 1307.758269,
      "bar_pct": 6,
      "market_cap_gbp_b": 58.472,
      "market_cap_usd_b": 78.728,
      "avg_volume_m": 470.1,
      "cmc_rank": 4,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 497000263,
      "vol_1w": 3290715726,
      "vol_1m": 16871607239,
      "news": [
        {
          "title": "Top Cryptocurrencies Mixed; Bitcoin Holds Above $63,000",
          "publisher": "MT Newswires",
          "url": "https://finance.yahoo.com/markets/crypto/articles/top-cryptocurrencies-mixed-bitcoin-holds-195600234.html",
          "published": 1785354960,
          "sentiment": 0.202
        },
        {
          "title": "Why Does XRP Fall Faster Than Every Other Major Coin?",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/xrp-price-crowded-longs-whale-selling/",
          "published": 1785337200,
          "sentiment": 0.0
        },
        {
          "title": "1inch's Shared Liquidity Layer Aqua Goes Live",
          "publisher": "decrypt",
          "url": "https://decrypt.co/374533/1inchs-shared-liquidity-layer-aqua-goes-live",
          "published": 1785239606,
          "sentiment": 0.34
        },
        {
          "title": "Top Cryptocurrencies Mixed; Bitcoin Holds Above $64,000",
          "publisher": "MT Newswires",
          "url": "https://finance.yahoo.com/markets/crypto/articles/top-cryptocurrencies-mixed-bitcoin-holds-200122904.html",
          "published": 1785182482,
          "sentiment": 0.202
        },
        {
          "title": "Top Cryptocurrencies Fall; Bitcoin Holds Above $64,000",
          "publisher": "MT Newswires",
          "url": "https://finance.yahoo.com/markets/crypto/articles/top-cryptocurrencies-fall-bitcoin-holds-200416069.html",
          "published": 1784923456,
          "sentiment": 0.202
        }
      ],
      "news_sentiment": 0.189
    },
    {
      "ticker": "ADA",
      "yf_ticker": "ADA-USD",
      "company_name": "Cardano",
      "category": "layer1",
      "exchange": "Crypto",
      "price_gbp": "0.1265",
      "price_usd": 0.170346,
      "change_1d": "+4.90%",
      "change_1w": "+0.81%",
      "change_1m": "+18.29%",
      "change_ytd": "-48.79%",
      "return_1yr": "-49%",
      "low_gbp": "0.1067",
      "low_usd": 0.143637,
      "high_gbp": "0.7153",
      "high_usd": 0.963099,
      "bar_pct": 3,
      "market_cap_gbp_b": 4.618,
      "market_cap_usd_b": 6.218,
      "avg_volume_m": 231.56,
      "cmc_rank": 15,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 339098411,
      "vol_1w": 1620890469,
      "vol_1m": 9606539081,
      "news": [
        {
          "title": "Cardano Founder Calls Trump 'Disgusting', Though Harris Administration Would Have Been 'Worse' for Crypto",
          "publisher": "Benzinga",
          "url": "https://finance.yahoo.com/markets/crypto/articles/cardano-founder-calls-trump-disgusting-023048636.html",
          "published": 1785378648,
          "sentiment": -0.758
        },
        {
          "title": "Top Cryptocurrencies Mixed; Bitcoin Holds Above $63,000",
          "publisher": "MT Newswires",
          "url": "https://finance.yahoo.com/markets/crypto/articles/top-cryptocurrencies-mixed-bitcoin-holds-195600234.html",
          "published": 1785354960,
          "sentiment": 0.202
        },
        {
          "title": "A Surprise Rate Hike? Cardano (ADA) and Bittensor (TAO) Climb Before the Fed Speaks",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/cardano-bittensor-rise-fed-rate-decision/",
          "published": 1785326007,
          "sentiment": 0.273
        },
        {
          "title": "Cardano Could Fall 40%\u201350% as ADA Price Forms Two Bearish Patterns",
          "publisher": "FX Empire",
          "url": "https://finance.yahoo.com/markets/crypto/articles/cardano-could-fall-40-50-092318263.html",
          "published": 1785316998,
          "sentiment": 0.0
        },
        {
          "title": "Cardano\u2019s Hoskinson Says \u2018Best Days Are Ahead\u2019: ADA Price Down 95% From Top",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/hoskinson-cardano-best-days-ahead-ada/",
          "published": 1785206515,
          "sentiment": 0.202
        }
      ],
      "news_sentiment": -0.016
    },
    {
      "ticker": "AVAX",
      "yf_ticker": "AVAX-USD",
      "company_name": "Avalanche",
      "category": "layer1",
      "exchange": "Crypto",
      "price_gbp": "4.79",
      "price_usd": 6.451666,
      "change_1d": "+1.31%",
      "change_1w": "+2.32%",
      "change_1m": "-1.40%",
      "change_ytd": "-47.58%",
      "return_1yr": "-48%",
      "low_gbp": "4.38",
      "low_usd": 5.892212,
      "high_gbp": "26",
      "high_usd": 35.23229,
      "bar_pct": 2,
      "market_cap_gbp_b": 2.069,
      "market_cap_usd_b": 2.786,
      "avg_volume_m": 173.14,
      "cmc_rank": 27,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 176108360,
      "vol_1w": 1212001833,
      "vol_1m": 4864730888,
      "news": [
        {
          "title": "Ethereum and solana are getting busier \u2014 and cheaper. What's going on?",
          "publisher": "Yahoo Finance Video",
          "url": "https://finance.yahoo.com/video/ethereum-solana-getting-busier-cheaper-173000356.html",
          "published": 1785259800,
          "sentiment": 0.0
        },
        {
          "title": "Aptos climbs to the top 4 blockchains in transaction count",
          "publisher": "TheStreet",
          "url": "https://www.thestreet.com/crypto/innovation/aptos-climbs-to-the-top-4-blockchains-in-transaction-count",
          "published": 1784923380,
          "sentiment": 0.202
        }
      ],
      "news_sentiment": 0.101
    },
    {
      "ticker": "XRP",
      "yf_ticker": "XRP-USD",
      "company_name": "XRP",
      "category": "payments",
      "exchange": "Crypto",
      "price_gbp": "0.8055",
      "price_usd": 1.08456,
      "change_1d": "+0.97%",
      "change_1w": "-2.24%",
      "change_1m": "+4.33%",
      "change_ytd": "-41.04%",
      "return_1yr": "-41%",
      "low_gbp": "0.7710",
      "low_usd": 1.038103,
      "high_gbp": "2.46",
      "high_usd": 3.316052,
      "bar_pct": 2,
      "market_cap_gbp_b": 50.371,
      "market_cap_usd_b": 67.821,
      "avg_volume_m": 989.93,
      "cmc_rank": 6,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 1317525506,
      "vol_1w": 6929501631,
      "vol_1m": 34331286245,
      "news": [
        {
          "title": "$8.5 million in XRP stolen in fake investment scam",
          "publisher": "TheStreet",
          "url": "https://www.thestreet.com/crypto/markets/8-5-million-in-xrp-stolen-in-fake-investment-scam",
          "published": 1785441309,
          "sentiment": -0.875
        },
        {
          "title": "XRP Price Prediction: How Low Will XRP Drop in 2026 if the CLARITY Act Doesn\u2019t Pass?",
          "publisher": "24/7 Wall St.",
          "url": "https://247wallst.com/investing/cryptocurrency/2026/07/30/xrp-price-prediction-how-low-will-xrp-drop-in-2026-if-the-clarity-act-doesnt-pass/",
          "published": 1785432357,
          "sentiment": 0.06
        },
        {
          "title": "A New Crypto Index Just Launched. Here's Why That's Bullish for Ethereum, Solana, and Hyperliquid.",
          "publisher": "Motley Fool",
          "url": "https://www.fool.com/investing/2026/07/30/a-new-crypto-index-just-launched-heres-why-thats-b/",
          "published": 1785430200,
          "sentiment": 0.128
        },
        {
          "title": "Coinbase beats much of customer lawsuit over US token sales",
          "publisher": "Reuters",
          "url": "https://finance.yahoo.com/markets/crypto/articles/coinbase-beats-much-customer-lawsuit-164519676.html",
          "published": 1785430182,
          "sentiment": -0.226
        },
        {
          "title": "Central Bank of Ireland Clears First Public-Chain Fund on XRPL, Setting EU Compliance Template",
          "publisher": "Coinspeaker",
          "url": "https://www.coinspeaker.com/tokenized-fund-xrp-ripple-ledger-cbi-approval/",
          "published": 1785409432,
          "sentiment": 0.077
        }
      ],
      "news_sentiment": -0.167
    },
    {
      "ticker": "XLM",
      "yf_ticker": "XLM-USD",
      "company_name": "Stellar",
      "category": "payments",
      "exchange": "Crypto",
      "price_gbp": "0.1279",
      "price_usd": 0.172179,
      "change_1d": "+1.13%",
      "change_1w": "-5.63%",
      "change_1m": "-5.58%",
      "change_ytd": "-14.18%",
      "return_1yr": "-14%",
      "low_gbp": "0.1065",
      "low_usd": 0.143327,
      "high_gbp": "0.3362",
      "high_usd": 0.452633,
      "bar_pct": 9,
      "market_cap_gbp_b": 4.377,
      "market_cap_usd_b": 5.893,
      "avg_volume_m": 119.34,
      "cmc_rank": 16,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 107962634,
      "vol_1w": 835386995,
      "vol_1m": 7030775918,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "TRX",
      "yf_ticker": "TRX-USD",
      "company_name": "TRON",
      "category": "payments",
      "exchange": "Crypto",
      "price_gbp": "0.2441",
      "price_usd": 0.328718,
      "change_1d": "+0.92%",
      "change_1w": "+0.15%",
      "change_1m": "+4.41%",
      "change_ytd": "+15.60%",
      "return_1yr": "+16%",
      "low_gbp": "0.2000",
      "low_usd": 0.269273,
      "high_gbp": "0.2786",
      "high_usd": 0.375055,
      "bar_pct": 56,
      "market_cap_gbp_b": 23.166,
      "market_cap_usd_b": 31.191,
      "avg_volume_m": 342.07,
      "cmc_rank": 8,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 344867748,
      "vol_1w": 2394521720,
      "vol_1m": 11162875967,
      "news": [
        {
          "title": "TRON (TRX) New Accounts Jump 42.87% to One-Month High",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/tron-new-accounts-one-month-high/",
          "published": 1785331715,
          "sentiment": 0.0
        },
        {
          "title": "Tron TRX Ends 16% Slide With Two Bullish Signals",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/trx-price-bottom-tron-recovery/",
          "published": 1785085200,
          "sentiment": 0.0
        },
        {
          "title": "Crypto Payments Firm Triple-A Hit by $9.7 Million Wallet Drain",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/triple-a-exploit-9m-wallet-drain/",
          "published": 1784965659,
          "sentiment": 0.0
        },
        {
          "title": "Aptos climbs to the top 4 blockchains in transaction count",
          "publisher": "TheStreet",
          "url": "https://www.thestreet.com/crypto/innovation/aptos-climbs-to-the-top-4-blockchains-in-transaction-count",
          "published": 1784923380,
          "sentiment": 0.202
        },
        {
          "title": "3 Altcoins That Could Reach New All-Time Highs This Weekend",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/altcoins-ath-fourth-weekend-july-2026/",
          "published": 1784908800,
          "sentiment": 0.026
        }
      ],
      "news_sentiment": 0.046
    },
    {
      "ticker": "SUI",
      "yf_ticker": "SUI20947-USD",
      "company_name": "Sui",
      "category": "emerging",
      "exchange": "Crypto",
      "price_gbp": "0.5171",
      "price_usd": 0.696265,
      "change_1d": "+2.12%",
      "change_1w": "-6.83%",
      "change_1m": "+0.69%",
      "change_ytd": "-50.36%",
      "return_1yr": "-50%",
      "low_gbp": "0.5053",
      "low_usd": 0.68029,
      "high_gbp": "2.98",
      "high_usd": 4.010463,
      "bar_pct": 1,
      "market_cap_gbp_b": 2.096,
      "market_cap_usd_b": 2.821,
      "avg_volume_m": 159.0,
      "cmc_rank": 26,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 149039945,
      "vol_1w": 1113026773,
      "vol_1m": 3256209023,
      "news": [
        {
          "title": "3 Token Unlocks to Watch in This Week",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/crypto-token-unlocks-sui-eigen-kmno-july/",
          "published": 1785135407,
          "sentiment": 0.0
        },
        {
          "title": "Aptos climbs to the top 4 blockchains in transaction count",
          "publisher": "TheStreet",
          "url": "https://www.thestreet.com/crypto/innovation/aptos-climbs-to-the-top-4-blockchains-in-transaction-count",
          "published": 1784923380,
          "sentiment": 0.202
        }
      ],
      "news_sentiment": 0.101
    },
    {
      "ticker": "HBAR",
      "yf_ticker": "HBAR-USD",
      "company_name": "Hedera",
      "category": "emerging",
      "exchange": "Crypto",
      "price_gbp": "0.0509",
      "price_usd": 0.068511,
      "change_1d": "+1.68%",
      "change_1w": "-4.39%",
      "change_1m": "-1.15%",
      "change_ytd": "-35.48%",
      "return_1yr": "-35%",
      "low_gbp": "0.0489",
      "low_usd": 0.065892,
      "high_gbp": "0.1980",
      "high_usd": 0.266594,
      "bar_pct": 1,
      "market_cap_gbp_b": 2.228,
      "market_cap_usd_b": 3.0,
      "avg_volume_m": 42.87,
      "cmc_rank": 25,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 34340130,
      "vol_1w": 300074114,
      "vol_1m": 1675122702,
      "news": [
        {
          "title": "XRP vs XLM vs HBAR: Which Payment Crypto Are Institutions Actually Using?",
          "publisher": "24/7 Wall St.",
          "url": "https://247wallst.com/investing/cryptocurrency/2026/07/27/xrp-vs-xlm-vs-hbar-which-payment-crypto-are-institutions-actually-using/",
          "published": 1785158089,
          "sentiment": 0.0
        }
      ],
      "news_sentiment": 0.0
    },
    {
      "ticker": "ALGO",
      "yf_ticker": "ALGO-USD",
      "company_name": "Algorand",
      "category": "emerging",
      "exchange": "Crypto",
      "price_gbp": "0.0590",
      "price_usd": 0.07946,
      "change_1d": "+3.63%",
      "change_1w": "-4.16%",
      "change_1m": "-3.92%",
      "change_ytd": "-27.88%",
      "return_1yr": "-28%",
      "low_gbp": "0.0574",
      "low_usd": 0.077299,
      "high_gbp": "0.2093",
      "high_usd": 0.281794,
      "bar_pct": 1,
      "market_cap_gbp_b": 0.529,
      "market_cap_usd_b": 0.713,
      "avg_volume_m": 20.53,
      "cmc_rank": 65,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 20066208,
      "vol_1w": 143688387,
      "vol_1m": 639741692,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "MINA",
      "yf_ticker": "MINA-USD",
      "company_name": "Mina",
      "category": "emerging",
      "exchange": "Crypto",
      "price_gbp": "0.0315",
      "price_usd": 0.042361,
      "change_1d": "+2.35%",
      "change_1w": "-5.08%",
      "change_1m": "+11.52%",
      "change_ytd": "-43.93%",
      "return_1yr": "-44%",
      "low_gbp": "0.0280",
      "low_usd": 0.037691,
      "high_gbp": "0.1559",
      "high_usd": 0.209885,
      "bar_pct": 3,
      "market_cap_gbp_b": 0.04,
      "market_cap_usd_b": 0.055,
      "avg_volume_m": 3.87,
      "cmc_rank": 312,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 3199975,
      "vol_1w": 27090512,
      "vol_1m": 153994054,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "POL",
      "yf_ticker": "POL-USD",
      "company_name": "Polygon (MATIC)",
      "category": "infra",
      "exchange": "Crypto",
      "price_gbp": "0.0529",
      "price_usd": 0.071167,
      "change_1d": "+0.07%",
      "change_1w": "-6.41%",
      "change_1m": "+2.63%",
      "change_ytd": "-29.14%",
      "return_1yr": "-29%",
      "low_gbp": "0.0509",
      "low_usd": 0.068524,
      "high_gbp": "0.2138",
      "high_usd": 0.287869,
      "bar_pct": 1,
      "market_cap_gbp_b": 0.565,
      "market_cap_usd_b": 0.761,
      "avg_volume_m": 26.41,
      "cmc_rank": 62,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 23756782,
      "vol_1w": 184854891,
      "vol_1m": 980478064,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "DOT",
      "yf_ticker": "DOT-USD",
      "company_name": "Polkadot",
      "category": "infra",
      "exchange": "Crypto",
      "price_gbp": "0.5747",
      "price_usd": 0.773749,
      "change_1d": "+1.86%",
      "change_1w": "-5.35%",
      "change_1m": "-5.70%",
      "change_ytd": "-56.77%",
      "return_1yr": "-57%",
      "low_gbp": "0.5631",
      "low_usd": 0.758151,
      "high_gbp": "3.37",
      "high_usd": 4.539353,
      "bar_pct": 1,
      "market_cap_gbp_b": 0.974,
      "market_cap_usd_b": 1.312,
      "avg_volume_m": 74.63,
      "cmc_rank": 44,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 87689050,
      "vol_1w": 522434619,
      "vol_1m": 2518423750,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "LINK",
      "yf_ticker": "LINK-USD",
      "company_name": "Chainlink",
      "category": "infra",
      "exchange": "Crypto",
      "price_gbp": "6.29",
      "price_usd": 8.471614,
      "change_1d": "+3.01%",
      "change_1w": "-0.23%",
      "change_1m": "+18.15%",
      "change_ytd": "-30.52%",
      "return_1yr": "-31%",
      "low_gbp": "5.34",
      "low_usd": 7.183384,
      "high_gbp": "20",
      "high_usd": 26.746351,
      "bar_pct": 7,
      "market_cap_gbp_b": 4.707,
      "market_cap_usd_b": 6.338,
      "avg_volume_m": 173.47,
      "cmc_rank": 14,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 202480114,
      "vol_1w": 1214264123,
      "vol_1m": 5388405177,
      "news": [
        {
          "title": "Ethereum Institutional Closes Ecosystem Funding Round With +100 Backers",
          "publisher": "Bankless",
          "url": "https://www.bankless.com/read/news/ethereum-institutional-closes-ecosystem-funding-round-with-100-backers",
          "published": 1785353535,
          "sentiment": 0.0
        },
        {
          "title": "WEMIX and Garden Hacks Add to Record 2026 Crypto Breaches",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/wemix-garden-hacks-2026-crypto-trend/",
          "published": 1785149214,
          "sentiment": 0.0
        }
      ],
      "news_sentiment": 0.0
    },
    {
      "ticker": "DOGE",
      "yf_ticker": "DOGE-USD",
      "company_name": "Dogecoin",
      "category": "meme",
      "exchange": "Crypto",
      "price_gbp": "0.0524",
      "price_usd": 0.070555,
      "change_1d": "+1.44%",
      "change_1w": "+1.52%",
      "change_1m": "-2.06%",
      "change_ytd": "-39.84%",
      "return_1yr": "-40%",
      "low_gbp": "0.0513",
      "low_usd": 0.069106,
      "high_gbp": "0.2149",
      "high_usd": 0.289332,
      "bar_pct": 1,
      "market_cap_gbp_b": 8.137,
      "market_cap_usd_b": 10.956,
      "avg_volume_m": 564.8,
      "cmc_rank": 10,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 511961232,
      "vol_1w": 3953600142,
      "vol_1m": 15958908344,
      "news": [
        {
          "title": "Coinbase beats much of customer lawsuit over US token sales",
          "publisher": "Reuters",
          "url": "https://finance.yahoo.com/markets/crypto/articles/coinbase-beats-much-customer-lawsuit-164519676.html",
          "published": 1785430182,
          "sentiment": -0.226
        },
        {
          "title": "Top Cryptocurrencies Mixed; Bitcoin Holds Above $63,000",
          "publisher": "MT Newswires",
          "url": "https://finance.yahoo.com/markets/crypto/articles/top-cryptocurrencies-mixed-bitcoin-holds-195600234.html",
          "published": 1785354960,
          "sentiment": 0.202
        },
        {
          "title": "Dogecoin, Shiba Inu Wins 'Good for Every Legitimate Meme Project,' Says Analyst: 'Ecosystem Has a Better Chance of Winning'",
          "publisher": "Benzinga",
          "url": "https://finance.yahoo.com/markets/crypto/articles/dogecoin-shiba-inu-wins-good-042122416.html",
          "published": 1785298882,
          "sentiment": 0.931
        },
        {
          "title": "Bitcoin, Ethereum, XRP, Dogecoin Gain Ahead of Fed Rate Cut Decision: Analyst Asks Investors to 'Mark Your Calendar' for Next BTC Bottom",
          "publisher": "Benzinga",
          "url": "https://finance.yahoo.com/markets/crypto/articles/bitcoin-ethereum-xrp-dogecoin-gain-020400354.html",
          "published": 1785290640,
          "sentiment": 0.318
        },
        {
          "title": "Robinhood Chain\u2019s Trading Volumes Slump As Memecoin Interest Fades",
          "publisher": "CryptoProwl",
          "url": "https://www.cryptoprowl.com/releases/robinhood-chains-trading-volumes-slump-as-memecoin-interest-fades-6275",
          "published": 1785267780,
          "sentiment": 0.459
        }
      ],
      "news_sentiment": 0.337
    },
    {
      "ticker": "PEPE",
      "yf_ticker": "PEPE24478-USD",
      "company_name": "Pepe",
      "category": "meme",
      "exchange": "Crypto",
      "price_gbp": "0.00000207",
      "price_usd": 3e-06,
      "change_1d": "+3.37%",
      "change_1w": "-0.11%",
      "change_1m": "+19.85%",
      "change_ytd": "-31.05%",
      "return_1yr": "-31%",
      "low_gbp": "0.00000173",
      "low_usd": 2e-06,
      "high_gbp": "0.00000922",
      "high_usd": 1.2e-05,
      "bar_pct": 5,
      "market_cap_gbp_b": 0.855,
      "market_cap_usd_b": 1.151,
      "avg_volume_m": 166.91,
      "cmc_rank": 49,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 152303847,
      "vol_1w": 1168386513,
      "vol_1m": 4665653031,
      "news": [
        {
          "title": "Trader Turns $50K Into Nearly $1M on Robinhood Chain's Top Memecoin: Arkham",
          "publisher": "CCN",
          "url": "https://www.ccn.com/news/crypto/trader-turns-44k-nearly-1m-robinhood-chain-memecoin-pons/",
          "published": 1785249211,
          "sentiment": 0.202
        }
      ],
      "news_sentiment": 0.202
    },
    {
      "ticker": "TAO",
      "yf_ticker": "TAO-USD",
      "company_name": "Bittensor",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "143",
      "price_usd": 193.004271,
      "change_1d": "+2.44%",
      "change_1w": "-0.42%",
      "change_1m": "-4.07%",
      "change_ytd": "-11.74%",
      "return_1yr": "-12%",
      "low_gbp": "113",
      "low_usd": 152.224218,
      "high_gbp": "370",
      "high_usd": 497.771996,
      "bar_pct": 12,
      "market_cap_gbp_b": 1.603,
      "market_cap_usd_b": 2.158,
      "avg_volume_m": 80.89,
      "cmc_rank": 34,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 104189964,
      "vol_1w": 566248644,
      "vol_1m": 3529009956,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "FET",
      "yf_ticker": "FET-USD",
      "company_name": "ASI Alliance",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.1080",
      "price_usd": 0.14543,
      "change_1d": "+6.91%",
      "change_1w": "-4.67%",
      "change_1m": "-15.02%",
      "change_ytd": "-26.81%",
      "return_1yr": "-27%",
      "low_gbp": "0.1023",
      "low_usd": 0.137684,
      "high_gbp": "0.5596",
      "high_usd": 0.753455,
      "bar_pct": 1,
      "market_cap_gbp_b": 0.242,
      "market_cap_usd_b": 0.326,
      "avg_volume_m": 45.17,
      "cmc_rank": 92,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 60820752,
      "vol_1w": 316204075,
      "vol_1m": 1310608805,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "RNDR",
      "yf_ticker": "RNDR-USD",
      "company_name": "Render",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "1.06",
      "price_usd": 1.421212,
      "change_1d": "+2.61%",
      "change_1w": "-4.01%",
      "change_1m": "-6.46%",
      "change_ytd": "+10.68%",
      "return_1yr": "+11%",
      "low_gbp": "0.8983",
      "low_usd": 1.209424,
      "high_gbp": "3.11",
      "high_usd": 4.180882,
      "bar_pct": 7,
      "market_cap_gbp_b": 0.548,
      "market_cap_usd_b": 0.737,
      "avg_volume_m": 22.0,
      "cmc_rank": 63,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 23317826,
      "vol_1w": 154014045,
      "vol_1m": 745758783,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "OCEAN",
      "yf_ticker": "OCEAN-USD",
      "company_name": "Ocean Protocol",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.0000000010",
      "price_usd": 0.0,
      "change_1d": "-10.46%",
      "change_1w": "+356.44%",
      "change_1m": "+356.44%",
      "change_ytd": "-100.00%",
      "return_1yr": "-100%",
      "low_gbp": "0.0647",
      "low_usd": 0.087176,
      "high_gbp": "0.2683",
      "high_usd": 0.361261,
      "bar_pct": 1,
      "market_cap_gbp_b": null,
      "market_cap_usd_b": null,
      "avg_volume_m": 0.03,
      "cmc_rank": 4203,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 19880,
      "vol_1w": 232174,
      "vol_1m": 1172044,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "GRT",
      "yf_ticker": "GRT-USD",
      "company_name": "The Graph",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.0111",
      "price_usd": 0.014879,
      "change_1d": "+0.23%",
      "change_1w": "-6.22%",
      "change_1m": "-14.58%",
      "change_ytd": "-55.25%",
      "return_1yr": "-55%",
      "low_gbp": "0.0111",
      "low_usd": 0.014894,
      "high_gbp": "0.0754",
      "high_usd": 0.101488,
      "bar_pct": 1,
      "market_cap_gbp_b": 0.121,
      "market_cap_usd_b": 0.162,
      "avg_volume_m": 9.8,
      "cmc_rank": 134,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 9445258,
      "vol_1w": 68597616,
      "vol_1m": 358527193,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "AGIX",
      "yf_ticker": "AGIX-USD",
      "company_name": "SingularityNET",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.0463",
      "price_usd": 0.062331,
      "change_1d": "+4.67%",
      "change_1w": "-5.69%",
      "change_1m": "-15.90%",
      "change_ytd": "-27.31%",
      "return_1yr": "-27%",
      "low_gbp": "0.0132",
      "low_usd": 0.017819,
      "high_gbp": "0.6922",
      "high_usd": 0.931946,
      "bar_pct": 5,
      "market_cap_gbp_b": null,
      "market_cap_usd_b": null,
      "avg_volume_m": 0.03,
      "cmc_rank": 4630,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 14996,
      "vol_1w": 178490,
      "vol_1m": 296794,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "NMR",
      "yf_ticker": "NMR-USD",
      "company_name": "Numeraire",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "6.27",
      "price_usd": 8.445651,
      "change_1d": "+4.13%",
      "change_1w": "-6.77%",
      "change_1m": "-6.78%",
      "change_ytd": "-11.61%",
      "return_1yr": "-12%",
      "low_gbp": "4.68",
      "low_usd": 6.303896,
      "high_gbp": "16",
      "high_usd": 21.000893,
      "bar_pct": 15,
      "market_cap_gbp_b": 0.047,
      "market_cap_usd_b": 0.064,
      "avg_volume_m": 4.21,
      "cmc_rank": 284,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 4632549,
      "vol_1w": 29486848,
      "vol_1m": 137221722,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "ALT",
      "yf_ticker": "ALT-USD",
      "company_name": "AltLayer",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.00425107",
      "price_usd": 0.005724,
      "change_1d": "+1.58%",
      "change_1w": "-8.57%",
      "change_1m": "+2.55%",
      "change_ytd": "-50.01%",
      "return_1yr": "-50%",
      "low_gbp": "0.00417210",
      "low_usd": 0.005617,
      "high_gbp": "0.0290",
      "high_usd": 0.039098,
      "bar_pct": 1,
      "market_cap_gbp_b": 0.029,
      "market_cap_usd_b": 0.039,
      "avg_volume_m": 2.33,
      "cmc_rank": 400,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 4427957,
      "vol_1w": 16285600,
      "vol_1m": 112929860,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "AIOZ",
      "yf_ticker": "AIOZ-USD",
      "company_name": "AIOZ Network",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.0370",
      "price_usd": 0.049774,
      "change_1d": "+4.25%",
      "change_1w": "+0.80%",
      "change_1m": "-4.89%",
      "change_ytd": "-42.55%",
      "return_1yr": "-43%",
      "low_gbp": "0.0358",
      "low_usd": 0.048195,
      "high_gbp": "0.3372",
      "high_usd": 0.453952,
      "bar_pct": 1,
      "market_cap_gbp_b": 0.047,
      "market_cap_usd_b": 0.063,
      "avg_volume_m": 3.32,
      "cmc_rank": 286,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 3159883,
      "vol_1w": 23232690,
      "vol_1m": 112266138,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "ARKM",
      "yf_ticker": "ARKM-USD",
      "company_name": "Arkham",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.0701",
      "price_usd": 0.094436,
      "change_1d": "+0.54%",
      "change_1w": "-12.78%",
      "change_1m": "-14.50%",
      "change_ytd": "-46.48%",
      "return_1yr": "-46%",
      "low_gbp": "0.0700",
      "low_usd": 0.094316,
      "high_gbp": "0.4935",
      "high_usd": 0.664423,
      "bar_pct": 1,
      "market_cap_gbp_b": 0.016,
      "market_cap_usd_b": 0.021,
      "avg_volume_m": 4.48,
      "cmc_rank": 595,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 4771371,
      "vol_1w": 31355969,
      "vol_1m": 168913816,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "WLD",
      "yf_ticker": "WLD-USD",
      "company_name": "Worldcoin",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.2299",
      "price_usd": 0.309497,
      "change_1d": "+1.93%",
      "change_1w": "-19.19%",
      "change_1m": "-24.14%",
      "change_ytd": "-35.66%",
      "return_1yr": "-36%",
      "low_gbp": "0.1725",
      "low_usd": 0.232204,
      "high_gbp": "1.44",
      "high_usd": 1.934961,
      "bar_pct": 5,
      "market_cap_gbp_b": 0.82,
      "market_cap_usd_b": 1.104,
      "avg_volume_m": 123.59,
      "cmc_rank": 51,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 113753539,
      "vol_1w": 865153780,
      "vol_1m": 4473651005,
      "news": [
        {
          "title": "Worldcoin Crashes 10% After the Project Sells 217 Million Tokens for Funding",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/worldcoin-token-sales-price-crash/",
          "published": 1784970942,
          "sentiment": 0.0
        }
      ],
      "news_sentiment": 0.0
    },
    {
      "ticker": "NEAR",
      "yf_ticker": "NEAR-USD",
      "company_name": "NEAR Protocol",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "1.25",
      "price_usd": 1.686756,
      "change_1d": "+6.11%",
      "change_1w": "-10.81%",
      "change_1m": "-5.71%",
      "change_ytd": "+11.53%",
      "return_1yr": "+12%",
      "low_gbp": "0.7156",
      "low_usd": 0.963533,
      "high_gbp": "2.37",
      "high_usd": 3.190205,
      "bar_pct": 32,
      "market_cap_gbp_b": 1.631,
      "market_cap_usd_b": 2.197,
      "avg_volume_m": 130.89,
      "cmc_rank": 33,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 213163162,
      "vol_1w": 916223156,
      "vol_1m": 5177240315,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "ICP",
      "yf_ticker": "ICP-USD",
      "company_name": "Internet Computer",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "1.54",
      "price_usd": 2.07785,
      "change_1d": "+1.90%",
      "change_1w": "-4.05%",
      "change_1m": "-1.08%",
      "change_ytd": "-26.71%",
      "return_1yr": "-27%",
      "low_gbp": "1.53",
      "low_usd": 2.058189,
      "high_gbp": "6.67",
      "high_usd": 8.982771,
      "bar_pct": 1,
      "market_cap_gbp_b": 0.857,
      "market_cap_usd_b": 1.154,
      "avg_volume_m": 28.26,
      "cmc_rank": 48,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 33037051,
      "vol_1w": 197787254,
      "vol_1m": 1012023214,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "KAITO",
      "yf_ticker": "KAITO-USD",
      "company_name": "Kaito",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.8078",
      "price_usd": 1.087657,
      "change_1d": "-15.88%",
      "change_1w": "+3.55%",
      "change_1m": "+90.67%",
      "change_ytd": "+114.87%",
      "return_1yr": "+115%",
      "low_gbp": "0.2287",
      "low_usd": 0.307976,
      "high_gbp": "1.17",
      "high_usd": 1.569334,
      "bar_pct": 62,
      "market_cap_gbp_b": 0.195,
      "market_cap_usd_b": 0.263,
      "avg_volume_m": 73.71,
      "cmc_rank": 103,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 76469961,
      "vol_1w": 515995439,
      "vol_1m": 1288264425,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "VIRTUAL",
      "yf_ticker": "VIRTUAL-USD",
      "company_name": "Virtuals Protocol",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.4254",
      "price_usd": 0.572708,
      "change_1d": "+3.59%",
      "change_1w": "-6.57%",
      "change_1m": "+8.87%",
      "change_ytd": "-11.40%",
      "return_1yr": "-11%",
      "low_gbp": "0.3852",
      "low_usd": 0.518646,
      "high_gbp": "1.37",
      "high_usd": 1.839815,
      "bar_pct": 4,
      "market_cap_gbp_b": 0.28,
      "market_cap_usd_b": 0.377,
      "avg_volume_m": 43.88,
      "cmc_rank": 87,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 39549090,
      "vol_1w": 307152244,
      "vol_1m": 1732023502,
      "news": [],
      "news_sentiment": null
    }
  ]
};
