window.PRICES_DATA = {
  "updated": "2026-07-14 20:37",
  "fx_gbp_usd": 1.3386,
  "stocks": [
    {
      "ticker": "BTC",
      "yf_ticker": "BTC-USD",
      "company_name": "Bitcoin",
      "category": "bitcoin",
      "exchange": "Crypto",
      "price_gbp": "48215",
      "price_usd": 64539.232048,
      "change_1d": "+4.17%",
      "change_1w": "+1.44%",
      "change_1m": "+1.21%",
      "change_ytd": "-26.26%",
      "return_1yr": "-26%",
      "low_gbp": "43742",
      "low_usd": 58550.747788,
      "high_gbp": "93215",
      "high_usd": 124773.508231,
      "bar_pct": 9,
      "market_cap_gbp_b": 967.024,
      "market_cap_usd_b": 1294.423,
      "avg_volume_m": 25529.68,
      "cmc_rank": 1,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 30583681982,
      "vol_1w": 178707737311,
      "vol_1m": 835562135595,
      "news": [
        {
          "title": "Inside bitcoin ETF flows: What investors are doing now",
          "publisher": "Yahoo Finance Video",
          "url": "https://finance.yahoo.com/video/inside-bitcoin-etf-flows-investors-183000495.html",
          "published": 1784053800,
          "sentiment": 0.0
        },
        {
          "title": "Why bitcoin ETFs are losing money",
          "publisher": "Yahoo Finance Video",
          "url": "https://finance.yahoo.com/video/why-bitcoin-etfs-are-losing-money-163423250.html",
          "published": 1784046863,
          "sentiment": -0.382
        },
        {
          "title": "Strategy Raises $467 Million, Builds $3 Billion Cash Reserve Without Buying Bitcoin",
          "publisher": "GuruFocus.com",
          "url": "https://finance.yahoo.com/markets/stocks/articles/strategy-raises-467-million-builds-192849683.html",
          "published": 1784057329,
          "sentiment": 0.0
        },
        {
          "title": "CleanSpark Lands $6.6 Billion Data Center Lease With Global Tech Tenant",
          "publisher": "GuruFocus.com",
          "url": "https://finance.yahoo.com/technology/ai/articles/cleanspark-lands-6-6-billion-192729898.html",
          "published": 1784057249,
          "sentiment": 0.0
        },
        {
          "title": "Stock Market Today: Nasdaq Shows Strength; CrowdStrike Sprints Higher (Live Coverage)",
          "publisher": "Investor's Business Daily",
          "url": "https://www.investors.com/market-trend/stock-market-today/dow-jones-sp500-nasdaq-june-cpi-inflation-ibm-stock/?src=A00220&yptr=yahoo",
          "published": 1784056681,
          "sentiment": 0.494
        }
      ],
      "news_sentiment": 0.022
    },
    {
      "ticker": "ETH",
      "yf_ticker": "ETH-USD",
      "company_name": "Ethereum",
      "category": "layer1",
      "exchange": "Crypto",
      "price_gbp": "1401",
      "price_usd": 1874.688567,
      "change_1d": "+6.18%",
      "change_1w": "+5.00%",
      "change_1m": "+12.56%",
      "change_ytd": "-36.81%",
      "return_1yr": "-37%",
      "low_gbp": "1169",
      "low_usd": 1564.842843,
      "high_gbp": "3608",
      "high_usd": 4829.225542,
      "bar_pct": 9,
      "market_cap_gbp_b": 169.019,
      "market_cap_usd_b": 226.243,
      "avg_volume_m": 8280.43,
      "cmc_rank": 2,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 10331003304,
      "vol_1w": 57963007270,
      "vol_1m": 316328166853,
      "news": [
        {
          "title": "Crypto buyers may be emerging from their winter hibernation",
          "publisher": "Yahoo Finance",
          "url": "https://finance.yahoo.com/markets/crypto/article/crypto-buyers-may-be-emerging-from-their-winter-hibernation-135203854.html",
          "published": 1784037123,
          "sentiment": 0.0
        },
        {
          "title": "Bitcoin and ethereum prices today, Tuesday, July 14, 2026:",
          "publisher": "Yahoo Personal Finance",
          "url": "https://finance.yahoo.com/personal-finance/investing/article/bitcoin-and-ethereum-prices-today-tuesday-july-14-2026-123022806.html",
          "published": 1784032222,
          "sentiment": 0.0
        },
        {
          "title": "Eightco (ORBS) Highlights $90M OpenAI Stake in Holdings Update",
          "publisher": "Insider Monkey",
          "url": "https://finance.yahoo.com/markets/stocks/articles/eightco-orbs-highlights-90m-openai-180856136.html",
          "published": 1784052536,
          "sentiment": 0.0
        },
        {
          "title": "Ethereum Foundation Privacy Team Spins Out as EthSystems",
          "publisher": "Bankless",
          "url": "https://www.bankless.com/read/news/ethereum-foundation-privacy-team-spins-out-as-ethsystems",
          "published": 1784048388,
          "sentiment": 0.0
        },
        {
          "title": "Bitmine, SharpLink and Joe Lubin Back EthSystems\u2019 Institutional Ethereum Privacy Push",
          "publisher": "CryptoProwl",
          "url": "https://www.cryptoprowl.com/releases/bitmine-sharplink-and-joe-lubin-back-ethsystems-institutional-ethereum-privacy-push-6152",
          "published": 1784044740,
          "sentiment": 0.0
        }
      ],
      "news_sentiment": 0.0
    },
    {
      "ticker": "SOL",
      "yf_ticker": "SOL-USD",
      "company_name": "Solana",
      "category": "layer1",
      "exchange": "Crypto",
      "price_gbp": "58",
      "price_usd": 77.316228,
      "change_1d": "+3.44%",
      "change_1w": "-4.65%",
      "change_1m": "+14.37%",
      "change_ytd": "-37.91%",
      "return_1yr": "-38%",
      "low_gbp": "46",
      "low_usd": 62.157877,
      "high_gbp": "185",
      "high_usd": 247.556262,
      "bar_pct": 8,
      "market_cap_gbp_b": 33.64,
      "market_cap_usd_b": 45.03,
      "avg_volume_m": 1778.81,
      "cmc_rank": 7,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 1782572316,
      "vol_1w": 12451676134,
      "vol_1m": 73196277285,
      "news": [
        {
          "title": "SBI Holdings teams up with Solana on a new onchain market in Japan",
          "publisher": "TheStreet",
          "url": "https://www.thestreet.com/crypto/markets/sbi-holdings-teams-up-with-solana-on-a-new-onchain-market-in-japan",
          "published": 1784043883,
          "sentiment": 0.0
        },
        {
          "title": "Van Rossem Upgrade, SBI Fallout, and a DRep Deadlock Define Cardano\u2019s Pivotal Week",
          "publisher": "99bitcoins",
          "url": "https://99bitcoins.com/news/altcoins/cardano-drep-governance-van-rossem-sbi-holdings/",
          "published": 1784037516,
          "sentiment": -0.34
        },
        {
          "title": "Solana Price Forecast: Big Move Ahead for SOL According to This Metric",
          "publisher": "FX Empire",
          "url": "https://finance.yahoo.com/markets/crypto/articles/solana-price-forecast-big-move-134240406.html",
          "published": 1784036560,
          "sentiment": 0.0
        },
        {
          "title": "Ripple\u2019s Biggest Shareholder Is Building Institutional XRP Lending in Japan",
          "publisher": "24/7 Wall St.",
          "url": "https://247wallst.com/investing/cryptocurrency/2026/07/14/ripples-biggest-shareholder-is-building-institutional-xrp-lending-in-japan/",
          "published": 1784035821,
          "sentiment": 0.0
        },
        {
          "title": "XRP Price to $0.54? 50% Crash Warning as SBI and Solana Partnership Hits Japan",
          "publisher": "CCN",
          "url": "https://www.ccn.com/news/crypto/xrp-price-bearish-predictions-sbi-solana-venture-japan/",
          "published": 1784035635,
          "sentiment": -0.625
        }
      ],
      "news_sentiment": -0.193
    },
    {
      "ticker": "BNB",
      "yf_ticker": "BNB-USD",
      "company_name": "BNB",
      "category": "layer1",
      "exchange": "Crypto",
      "price_gbp": "434",
      "price_usd": 580.623457,
      "change_1d": "+2.96%",
      "change_1w": "-0.17%",
      "change_1m": "-3.80%",
      "change_ytd": "-32.73%",
      "return_1yr": "-33%",
      "low_gbp": "408",
      "low_usd": 545.715777,
      "high_gbp": "980",
      "high_usd": 1311.712915,
      "bar_pct": 5,
      "market_cap_gbp_b": 58.464,
      "market_cap_usd_b": 78.258,
      "avg_volume_m": 504.61,
      "cmc_rank": 4,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 490659834,
      "vol_1w": 3532274811,
      "vol_1m": 20361221696,
      "news": [
        {
          "title": "Robinhood Chain Passes Ethereum in DEX Volume 2 Weeks After Launch",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/robinhood-chain-ethereum-dex-volume/",
          "published": 1784000619,
          "sentiment": 0.0
        },
        {
          "title": "Ondo launches true 24/7 minting and redemption for tokenized stocks",
          "publisher": "TheStreet",
          "url": "https://www.thestreet.com/crypto/innovation/ondo-launches-true-24-7-minting-and-redemption-for-tokenized-stocks",
          "published": 1783996200,
          "sentiment": 0.421
        },
        {
          "title": "Top Cryptocurrencies Lower; Bitcoin Holds Above $62,000 Level",
          "publisher": "MT Newswires",
          "url": "https://finance.yahoo.com/markets/crypto/articles/top-cryptocurrencies-lower-bitcoin-holds-200059472.html",
          "published": 1783972859,
          "sentiment": -0.103
        },
        {
          "title": "Binance Founder Moves Millions in Meme Coins to a Burn Address",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/cz-sends-millions-meme-coins-dead-address/",
          "published": 1783966640,
          "sentiment": 0.0
        },
        {
          "title": "5 Altcoins Stand to Gain From Tokenized Stocks, Grayscale Says",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/grayscale-altcoins-benefit-tokenized-stocks/",
          "published": 1783713508,
          "sentiment": 0.527
        }
      ],
      "news_sentiment": 0.169
    },
    {
      "ticker": "ADA",
      "yf_ticker": "ADA-USD",
      "company_name": "Cardano",
      "category": "layer1",
      "exchange": "Crypto",
      "price_gbp": "0.1219",
      "price_usd": 0.163226,
      "change_1d": "+3.92%",
      "change_1w": "-7.11%",
      "change_1m": "-1.89%",
      "change_ytd": "-50.93%",
      "return_1yr": "-51%",
      "low_gbp": "0.1072",
      "low_usd": 0.143472,
      "high_gbp": "0.7196",
      "high_usd": 0.96321,
      "bar_pct": 2,
      "market_cap_gbp_b": 4.448,
      "market_cap_usd_b": 5.954,
      "avg_volume_m": 279.79,
      "cmc_rank": 16,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 245258482,
      "vol_1w": 1958510637,
      "vol_1m": 11936980916,
      "news": [
        {
          "title": "Van Rossem Upgrade, SBI Fallout, and a DRep Deadlock Define Cardano\u2019s Pivotal Week",
          "publisher": "99bitcoins",
          "url": "https://99bitcoins.com/news/altcoins/cardano-drep-governance-van-rossem-sbi-holdings/",
          "published": 1784037516,
          "sentiment": -0.34
        },
        {
          "title": "Top Cryptocurrencies Lower; Bitcoin Holds Above $62,000 Level",
          "publisher": "MT Newswires",
          "url": "https://finance.yahoo.com/markets/crypto/articles/top-cryptocurrencies-lower-bitcoin-holds-200059472.html",
          "published": 1783972859,
          "sentiment": -0.103
        },
        {
          "title": "Cardano Price Climbs, but Its DeFi Engine Is Quietly Collapsing",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/cardano-price-defi-liquidity-collapse-analysis/",
          "published": 1783695600,
          "sentiment": -0.421
        },
        {
          "title": "Charles Hoskinson Denies Retirement Rumor That Reached London Cab Drivers",
          "publisher": "Cryptonews",
          "url": "https://cryptonews.com/news/charles-hoskinson-cardano-exit-rumors-denied/",
          "published": 1783680360,
          "sentiment": -0.34
        },
        {
          "title": "Charles Hoskinson Addresses Rumors He Is Quitting Cardano",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/hoskinson-denies-cardano-exit-rumors/",
          "published": 1783654298,
          "sentiment": 0.0
        }
      ],
      "news_sentiment": -0.241
    },
    {
      "ticker": "AVAX",
      "yf_ticker": "AVAX-USD",
      "company_name": "Avalanche",
      "category": "layer1",
      "exchange": "Crypto",
      "price_gbp": "4.98",
      "price_usd": 6.667788,
      "change_1d": "+3.53%",
      "change_1w": "-0.75%",
      "change_1m": "+3.40%",
      "change_ytd": "-45.83%",
      "return_1yr": "-46%",
      "low_gbp": "4.40",
      "low_usd": 5.890509,
      "high_gbp": "26",
      "high_usd": 35.281079,
      "bar_pct": 3,
      "market_cap_gbp_b": 2.151,
      "market_cap_usd_b": 2.879,
      "avg_volume_m": 152.72,
      "cmc_rank": 28,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 196480061,
      "vol_1w": 1069057093,
      "vol_1m": 6192368137,
      "news": [
        {
          "title": "How tokenized stocks could become a $3 trillion market",
          "publisher": "Yahoo Finance Video",
          "url": "https://finance.yahoo.com/video/how-tokenized-stocks-could-become-a-3-trillion-market-163106655.html",
          "published": 1783960266,
          "sentiment": 0.0
        },
        {
          "title": "BlackRock's BUIDL Nears $1 Billion Milestone on Avalanche as Real-World Asset Boom Accelerates",
          "publisher": "CCN",
          "url": "https://www.ccn.com/news/crypto/blackrock-buidl-avalanche-avax-price/",
          "published": 1783951635,
          "sentiment": 0.361
        },
        {
          "title": "5 Altcoins Stand to Gain From Tokenized Stocks, Grayscale Says",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/grayscale-altcoins-benefit-tokenized-stocks/",
          "published": 1783713508,
          "sentiment": 0.527
        },
        {
          "title": "NEC Taps Avalanche for Biometric-Verified Stablecoin Payments Framework",
          "publisher": "CryptoProwl",
          "url": "https://www.cryptoprowl.com/releases/nec-taps-avalanche-for-biometric-verified-stablecoin-payments-framework-6122",
          "published": 1783693020,
          "sentiment": 0.0
        },
        {
          "title": "Bitwise Drops 2 Altcoins From Flagship Crypto ETF: Will Hyperliquid Keep Its Seat?",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/bitwise-drops-two-altcoins-from-crypto-etf-index/",
          "published": 1783615163,
          "sentiment": 0.103
        }
      ],
      "news_sentiment": 0.198
    },
    {
      "ticker": "XRP",
      "yf_ticker": "XRP-USD",
      "company_name": "XRP",
      "category": "payments",
      "exchange": "Crypto",
      "price_gbp": "0.8339",
      "price_usd": 1.116252,
      "change_1d": "+5.18%",
      "change_1w": "-0.12%",
      "change_1m": "-1.53%",
      "change_ytd": "-39.31%",
      "return_1yr": "-39%",
      "low_gbp": "0.7759",
      "low_usd": 1.038645,
      "high_gbp": "2.66",
      "high_usd": 3.556293,
      "bar_pct": 3,
      "market_cap_gbp_b": 52.092,
      "market_cap_usd_b": 69.728,
      "avg_volume_m": 1037.97,
      "cmc_rank": 6,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 1126118075,
      "vol_1w": 7265802896,
      "vol_1m": 45764283743,
      "news": [
        {
          "title": "2 New Deals Make Ripple Productive Capital, but XRP Stays in Free Fall",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/ripple-xrp-utility-grows-price-falls/",
          "published": 1784052672,
          "sentiment": 0.665
        },
        {
          "title": "Ripple XRP Gains Attention After SWIFT Blockchain Expansion",
          "publisher": "Cryptonews",
          "url": "https://cryptonews.com/news/swift-ripple-xrp-blockchain-ledger-live/",
          "published": 1784049120,
          "sentiment": 0.604
        },
        {
          "title": "Ripple Is Now a Premier Member of the x402 Foundation, Alongside Visa and Mastercard",
          "publisher": "24/7 Wall St.",
          "url": "https://247wallst.com/investing/cryptocurrency/2026/07/14/ripple-is-now-a-premier-member-of-the-x402-foundation-alongside-visa-and-mastercard/",
          "published": 1784048882,
          "sentiment": 0.0
        },
        {
          "title": "XRP Holders Just Got Their Strongest Utility Signal Since the Lawsuit Ended",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/xrp-utility-ripple-stablecoin-migration/",
          "published": 1784037600,
          "sentiment": 0.25
        },
        {
          "title": "Ripple\u2019s Biggest Shareholder Is Building Institutional XRP Lending in Japan",
          "publisher": "24/7 Wall St.",
          "url": "https://247wallst.com/investing/cryptocurrency/2026/07/14/ripples-biggest-shareholder-is-building-institutional-xrp-lending-in-japan/",
          "published": 1784035821,
          "sentiment": 0.0
        }
      ],
      "news_sentiment": 0.304
    },
    {
      "ticker": "XLM",
      "yf_ticker": "XLM-USD",
      "company_name": "Stellar",
      "category": "payments",
      "exchange": "Crypto",
      "price_gbp": "0.1380",
      "price_usd": 0.184767,
      "change_1d": "+1.83%",
      "change_1w": "-3.09%",
      "change_1m": "+1.52%",
      "change_ytd": "-7.91%",
      "return_1yr": "-8%",
      "low_gbp": "0.1071",
      "low_usd": 0.143398,
      "high_gbp": "0.3758",
      "high_usd": 0.502966,
      "bar_pct": 12,
      "market_cap_gbp_b": 4.717,
      "market_cap_usd_b": 6.315,
      "avg_volume_m": 261.33,
      "cmc_rank": 13,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 148149046,
      "vol_1w": 1829302740,
      "vol_1m": 9940092575,
      "news": [
        {
          "title": "What Makes Repay Holdings (RPAY) Appear Attractive",
          "publisher": "Insider Monkey",
          "url": "https://finance.yahoo.com/markets/stocks/articles/makes-repay-holdings-rpay-appear-142825250.html",
          "published": 1783520905,
          "sentiment": 0.44
        }
      ],
      "news_sentiment": 0.44
    },
    {
      "ticker": "TRX",
      "yf_ticker": "TRX-USD",
      "company_name": "TRON",
      "category": "payments",
      "exchange": "Crypto",
      "price_gbp": "0.2429",
      "price_usd": 0.325091,
      "change_1d": "-0.11%",
      "change_1w": "-1.82%",
      "change_1m": "+2.13%",
      "change_ytd": "+14.33%",
      "return_1yr": "+14%",
      "low_gbp": "0.2012",
      "low_usd": 0.269328,
      "high_gbp": "0.2805",
      "high_usd": 0.375467,
      "bar_pct": 53,
      "market_cap_gbp_b": 23.04,
      "market_cap_usd_b": 30.84,
      "avg_volume_m": 364.62,
      "cmc_rank": 8,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 420964451,
      "vol_1w": 2552350249,
      "vol_1m": 14307085951,
      "news": [
        {
          "title": "Robinhood New Blockchain Hit $100 Million in TVL in 7 Days, But 90% of It Came From One Source",
          "publisher": "99bitcoins",
          "url": "https://99bitcoins.com/news/altcoins/robinhood-chain-tvl-first-week-morpho/",
          "published": 1783691381,
          "sentiment": 0.0
        }
      ],
      "news_sentiment": 0.0
    },
    {
      "ticker": "SUI",
      "yf_ticker": "SUI20947-USD",
      "company_name": "Sui",
      "category": "emerging",
      "exchange": "Crypto",
      "price_gbp": "0.5684",
      "price_usd": 0.760898,
      "change_1d": "+6.08%",
      "change_1w": "+3.58%",
      "change_1m": "+1.34%",
      "change_ytd": "-45.75%",
      "return_1yr": "-46%",
      "low_gbp": "0.5086",
      "low_usd": 0.680783,
      "high_gbp": "3.23",
      "high_usd": 4.326642,
      "bar_pct": 2,
      "market_cap_gbp_b": 2.304,
      "market_cap_usd_b": 3.083,
      "avg_volume_m": 179.21,
      "cmc_rank": 26,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 147436838,
      "vol_1w": 1254503148,
      "vol_1m": 8470350691,
      "news": [
        {
          "title": "The Worst Performing ETFs of 2026 So Far",
          "publisher": "etf.com",
          "url": "http://www.etf.com/sections/features/worst-performing-etfs-2026-so-far?utm_source=yahoo-finance&utm_medium=rss&utm_campaign=yahoo-finance-rss",
          "published": 1783722826,
          "sentiment": -0.625
        },
        {
          "title": "Bitwise Drops 2 Altcoins From Flagship Crypto ETF: Will Hyperliquid Keep Its Seat?",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/bitwise-drops-two-altcoins-from-crypto-etf-index/",
          "published": 1783615163,
          "sentiment": 0.103
        }
      ],
      "news_sentiment": -0.261
    },
    {
      "ticker": "HBAR",
      "yf_ticker": "HBAR-USD",
      "company_name": "Hedera",
      "category": "emerging",
      "exchange": "Crypto",
      "price_gbp": "0.0497",
      "price_usd": 0.066518,
      "change_1d": "+0.42%",
      "change_1w": "-7.06%",
      "change_1m": "-14.11%",
      "change_ytd": "-37.36%",
      "return_1yr": "-37%",
      "low_gbp": "0.0496",
      "low_usd": 0.066454,
      "high_gbp": "0.2172",
      "high_usd": 0.290755,
      "bar_pct": 1,
      "market_cap_gbp_b": 2.176,
      "market_cap_usd_b": 2.913,
      "avg_volume_m": 59.02,
      "cmc_rank": 27,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 51894335,
      "vol_1w": 413127857,
      "vol_1m": 1898164065,
      "news": [
        {
          "title": "Hedera-Based Bonzo Lend Loses $9 Million in Oracle Exploit",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/hedera-exploit-5-million-ethereum-bridge/",
          "published": 1783761847,
          "sentiment": -0.402
        }
      ],
      "news_sentiment": -0.402
    },
    {
      "ticker": "ALGO",
      "yf_ticker": "ALGO-USD",
      "company_name": "Algorand",
      "category": "emerging",
      "exchange": "Crypto",
      "price_gbp": "0.0634",
      "price_usd": 0.084824,
      "change_1d": "+1.92%",
      "change_1w": "-1.78%",
      "change_1m": "-5.76%",
      "change_ytd": "-23.02%",
      "return_1yr": "-23%",
      "low_gbp": "0.0605",
      "low_usd": 0.081023,
      "high_gbp": "0.2400",
      "high_usd": 0.321196,
      "bar_pct": 2,
      "market_cap_gbp_b": 0.568,
      "market_cap_usd_b": 0.761,
      "avg_volume_m": 21.08,
      "cmc_rank": 67,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 21402384,
      "vol_1w": 147547464,
      "vol_1m": 926088778,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "MINA",
      "yf_ticker": "MINA-USD",
      "company_name": "Mina",
      "category": "emerging",
      "exchange": "Crypto",
      "price_gbp": "0.0329",
      "price_usd": 0.044051,
      "change_1d": "+2.90%",
      "change_1w": "-7.32%",
      "change_1m": "+5.61%",
      "change_ytd": "-41.69%",
      "return_1yr": "-42%",
      "low_gbp": "0.0282",
      "low_usd": 0.037743,
      "high_gbp": "0.1777",
      "high_usd": 0.237877,
      "bar_pct": 3,
      "market_cap_gbp_b": 0.042,
      "market_cap_usd_b": 0.057,
      "avg_volume_m": 4.37,
      "cmc_rank": 351,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 3116821,
      "vol_1w": 30594019,
      "vol_1m": 152324556,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "POL",
      "yf_ticker": "POL-USD",
      "company_name": "Polygon (MATIC)",
      "category": "infra",
      "exchange": "Crypto",
      "price_gbp": "0.0631",
      "price_usd": 0.084451,
      "change_1d": "+2.73%",
      "change_1w": "+11.17%",
      "change_1m": "+12.49%",
      "change_ytd": "-15.92%",
      "return_1yr": "-16%",
      "low_gbp": "0.0511",
      "low_usd": 0.068398,
      "high_gbp": "0.2162",
      "high_usd": 0.289392,
      "bar_pct": 7,
      "market_cap_gbp_b": 0.674,
      "market_cap_usd_b": 0.902,
      "avg_volume_m": 38.63,
      "cmc_rank": 57,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 58384449,
      "vol_1w": 270428986,
      "vol_1m": 1106809609,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "DOT",
      "yf_ticker": "DOT-USD",
      "company_name": "Polkadot",
      "category": "infra",
      "exchange": "Crypto",
      "price_gbp": "0.6334",
      "price_usd": 0.847835,
      "change_1d": "+1.94%",
      "change_1w": "-1.31%",
      "change_1m": "-11.14%",
      "change_ytd": "-52.63%",
      "return_1yr": "-53%",
      "low_gbp": "0.6056",
      "low_usd": 0.810615,
      "high_gbp": "3.39",
      "high_usd": 4.541929,
      "bar_pct": 1,
      "market_cap_gbp_b": 1.073,
      "market_cap_usd_b": 1.436,
      "avg_volume_m": 84.7,
      "cmc_rank": 46,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 92846897,
      "vol_1w": 592884200,
      "vol_1m": 2617998375,
      "news": [
        {
          "title": "Bitwise Drops 2 Altcoins From Flagship Crypto ETF: Will Hyperliquid Keep Its Seat?",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/bitwise-drops-two-altcoins-from-crypto-etf-index/",
          "published": 1783615163,
          "sentiment": 0.103
        }
      ],
      "news_sentiment": 0.103
    },
    {
      "ticker": "LINK",
      "yf_ticker": "LINK-USD",
      "company_name": "Chainlink",
      "category": "infra",
      "exchange": "Crypto",
      "price_gbp": "6.18",
      "price_usd": 8.266435,
      "change_1d": "+5.31%",
      "change_1w": "+4.74%",
      "change_1m": "+5.57%",
      "change_ytd": "-32.21%",
      "return_1yr": "-32%",
      "low_gbp": "5.37",
      "low_usd": 7.183384,
      "high_gbp": "20",
      "high_usd": 26.746351,
      "bar_pct": 6,
      "market_cap_gbp_b": 4.49,
      "market_cap_usd_b": 6.011,
      "avg_volume_m": 150.62,
      "cmc_rank": 15,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 176039350,
      "vol_1w": 1054344778,
      "vol_1m": 5833386145,
      "news": [
        {
          "title": "Chainlink Hits Record 900,000 Wallets as CCIP Adoption Expands",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/chainlink-record-wallets-aave-ccip/",
          "published": 1784022487,
          "sentiment": 0.103
        },
        {
          "title": "US Government Sends $297 Million in Seized Crypto to Coinbase in One Day",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/us-government-297-million-crypto-coinbase-prime/",
          "published": 1783995857,
          "sentiment": 0.0
        },
        {
          "title": "Barclays, Morgan Stanley boost Robinhood price target by up to 50%",
          "publisher": "TheStreet",
          "url": "https://www.thestreet.com/crypto/markets/barclays-morgan-stanley-boost-robinhood-price-target-by-up-to-50",
          "published": 1783780200,
          "sentiment": 0.402
        },
        {
          "title": "Worst Crypto Prank Ever? Viral Prediction Market Pulls Off Shocking Joke",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/world-crypto-prank-solana-robinhood/",
          "published": 1783621807,
          "sentiment": -0.681
        },
        {
          "title": "Bitwise Drops 2 Altcoins From Flagship Crypto ETF: Will Hyperliquid Keep Its Seat?",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/bitwise-drops-two-altcoins-from-crypto-etf-index/",
          "published": 1783615163,
          "sentiment": 0.103
        }
      ],
      "news_sentiment": -0.015
    },
    {
      "ticker": "DOGE",
      "yf_ticker": "DOGE-USD",
      "company_name": "Dogecoin",
      "category": "meme",
      "exchange": "Crypto",
      "price_gbp": "0.0554",
      "price_usd": 0.074178,
      "change_1d": "+3.99%",
      "change_1w": "-0.36%",
      "change_1m": "-14.25%",
      "change_ytd": "-36.76%",
      "return_1yr": "-37%",
      "low_gbp": "0.0537",
      "low_usd": 0.071832,
      "high_gbp": "0.2162",
      "high_usd": 0.289384,
      "bar_pct": 1,
      "market_cap_gbp_b": 8.593,
      "market_cap_usd_b": 11.503,
      "avg_volume_m": 450.34,
      "cmc_rank": 10,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 415987060,
      "vol_1w": 3152371379,
      "vol_1m": 17491881700,
      "news": [
        {
          "title": "Bitcoin, Ethereum, XRP, Dogecoin Dip as Trump Reinstates Strait of Hormuz Blockade: Analyst Says Whales 'Actively Accumulating' BTC",
          "publisher": "Benzinga",
          "url": "https://finance.yahoo.com/markets/crypto/articles/bitcoin-ethereum-xrp-dogecoin-dip-014618534.html",
          "published": 1783993578,
          "sentiment": 0.318
        },
        {
          "title": "Top Cryptocurrencies Lower; Bitcoin Holds Above $62,000 Level",
          "publisher": "MT Newswires",
          "url": "https://finance.yahoo.com/markets/crypto/articles/top-cryptocurrencies-lower-bitcoin-holds-200059472.html",
          "published": 1783972859,
          "sentiment": -0.103
        },
        {
          "title": "Mark Yusko compares SpaceX's $2 trillion valuation to Dogecoin, warns lockup expiry could trigger deeper selloff",
          "publisher": "Moneywise",
          "url": "https://finance.yahoo.com/markets/stocks/articles/mark-yusko-compares-spacexs-2-171500659.html",
          "published": 1783962900,
          "sentiment": -0.103
        },
        {
          "title": "Hedge fund manager calls SpaceX equivalent of Dogecoin, says investors are Musk's exit liquidity",
          "publisher": "TheStreet",
          "url": "https://www.thestreet.com/crypto/markets/hedge-fund-manager-calls-spacex-equivalent-of-dogecoin-says-investors-are-musks-exit-liquidity",
          "published": 1783960070,
          "sentiment": 0.0
        },
        {
          "title": "Bitcoin, Ethereum, XRP, Dogecoin Consolidate as US-Iran Tensions Escalate: Analyst Says People Will Be 'Surprised' by Upcoming Bull Cycle",
          "publisher": "Benzinga",
          "url": "https://finance.yahoo.com/markets/crypto/articles/bitcoin-ethereum-xrp-dogecoin-consolidate-015612476.html",
          "published": 1783907772,
          "sentiment": -0.202
        }
      ],
      "news_sentiment": -0.018
    },
    {
      "ticker": "PEPE",
      "yf_ticker": "PEPE24478-USD",
      "company_name": "Pepe",
      "category": "meme",
      "exchange": "Crypto",
      "price_gbp": "0.00000210",
      "price_usd": 3e-06,
      "change_1d": "+4.75%",
      "change_1w": "+4.60%",
      "change_1m": "+1.00%",
      "change_ytd": "-30.35%",
      "return_1yr": "-30%",
      "low_gbp": "0.00000173",
      "low_usd": 2e-06,
      "high_gbp": "0.00001060",
      "high_usd": 1.4e-05,
      "bar_pct": 4,
      "market_cap_gbp_b": 0.869,
      "market_cap_usd_b": 1.163,
      "avg_volume_m": 133.45,
      "cmc_rank": 51,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 135533449,
      "vol_1w": 934135627,
      "vol_1m": 4432889527,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "TAO",
      "yf_ticker": "TAO-USD",
      "company_name": "Bittensor",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "152",
      "price_usd": 202.896955,
      "change_1d": "+2.07%",
      "change_1w": "-4.47%",
      "change_1m": "-23.34%",
      "change_ytd": "-7.21%",
      "return_1yr": "-7%",
      "low_gbp": "109",
      "low_usd": 145.650057,
      "high_gbp": "372",
      "high_usd": 498.180074,
      "bar_pct": 16,
      "market_cap_gbp_b": 1.686,
      "market_cap_usd_b": 2.257,
      "avg_volume_m": 171.41,
      "cmc_rank": 35,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 162860984,
      "vol_1w": 1199887145,
      "vol_1m": 6420579678,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "FET",
      "yf_ticker": "FET-USD",
      "company_name": "ASI Alliance",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.1216",
      "price_usd": 0.162808,
      "change_1d": "+2.71%",
      "change_1w": "-1.01%",
      "change_1m": "-19.65%",
      "change_ytd": "-18.07%",
      "return_1yr": "-18%",
      "low_gbp": "0.1055",
      "low_usd": 0.141246,
      "high_gbp": "0.6293",
      "high_usd": 0.84237,
      "bar_pct": 3,
      "market_cap_gbp_b": 0.273,
      "market_cap_usd_b": 0.365,
      "avg_volume_m": 41.06,
      "cmc_rank": 92,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 40126176,
      "vol_1w": 287394948,
      "vol_1m": 1720915002,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "RNDR",
      "yf_ticker": "RNDR-USD",
      "company_name": "Render",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "1.13",
      "price_usd": 1.511496,
      "change_1d": "+1.31%",
      "change_1w": "-4.16%",
      "change_1m": "-13.56%",
      "change_ytd": "+17.71%",
      "return_1yr": "+18%",
      "low_gbp": "0.9037",
      "low_usd": 1.209599,
      "high_gbp": "3.43",
      "high_usd": 4.588173,
      "bar_pct": 9,
      "market_cap_gbp_b": 0.586,
      "market_cap_usd_b": 0.784,
      "avg_volume_m": 25.04,
      "cmc_rank": 64,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 25454303,
      "vol_1w": 175289822,
      "vol_1m": 1204688957,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "OCEAN",
      "yf_ticker": "OCEAN-USD",
      "company_name": "Ocean Protocol",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.0835",
      "price_usd": 0.111751,
      "change_1d": "+1.25%",
      "change_1w": "-1.00%",
      "change_1m": "+11.23%",
      "change_ytd": "-25.79%",
      "return_1yr": "-26%",
      "low_gbp": "0.0650",
      "low_usd": 0.08704,
      "high_gbp": "0.2752",
      "high_usd": 0.368427,
      "bar_pct": 9,
      "market_cap_gbp_b": null,
      "market_cap_usd_b": null,
      "avg_volume_m": 0.04,
      "cmc_rank": 4341,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 44630,
      "vol_1w": 304607,
      "vol_1m": 2911844,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "GRT",
      "yf_ticker": "GRT-USD",
      "company_name": "The Graph",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.0131",
      "price_usd": 0.017597,
      "change_1d": "+3.02%",
      "change_1w": "-1.54%",
      "change_1m": "-9.81%",
      "change_ytd": "-47.07%",
      "return_1yr": "-47%",
      "low_gbp": "0.0128",
      "low_usd": 0.017176,
      "high_gbp": "0.0867",
      "high_usd": 0.116064,
      "bar_pct": 1,
      "market_cap_gbp_b": 0.143,
      "market_cap_usd_b": 0.192,
      "avg_volume_m": 12.88,
      "cmc_rank": 128,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 14734641,
      "vol_1w": 90125382,
      "vol_1m": 422259331,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "AGIX",
      "yf_ticker": "AGIX-USD",
      "company_name": "SingularityNET",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.0525",
      "price_usd": 0.070247,
      "change_1d": "+2.83%",
      "change_1w": "-5.63%",
      "change_1m": "-20.34%",
      "change_ytd": "-18.08%",
      "return_1yr": "-18%",
      "low_gbp": "0.0133",
      "low_usd": 0.017819,
      "high_gbp": "0.2729",
      "high_usd": 0.365305,
      "bar_pct": 15,
      "market_cap_gbp_b": null,
      "market_cap_usd_b": null,
      "avg_volume_m": 0.0,
      "cmc_rank": 4553,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 3886,
      "vol_1w": 24242,
      "vol_1m": 254238,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "NMR",
      "yf_ticker": "NMR-USD",
      "company_name": "Numeraire",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "7.38",
      "price_usd": 9.875715,
      "change_1d": "+4.23%",
      "change_1w": "+0.40%",
      "change_1m": "+20.15%",
      "change_ytd": "+3.36%",
      "return_1yr": "+3%",
      "low_gbp": "4.71",
      "low_usd": 6.305606,
      "high_gbp": "16",
      "high_usd": 20.785081,
      "bar_pct": 25,
      "market_cap_gbp_b": 0.055,
      "market_cap_usd_b": 0.074,
      "avg_volume_m": 5.56,
      "cmc_rank": 284,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 5951604,
      "vol_1w": 38912474,
      "vol_1m": 180631052,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "ALT",
      "yf_ticker": "ALT-USD",
      "company_name": "AltLayer",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.00475707",
      "price_usd": 0.006368,
      "change_1d": "+2.21%",
      "change_1w": "-0.04%",
      "change_1m": "-0.90%",
      "change_ytd": "-44.39%",
      "return_1yr": "-44%",
      "low_gbp": "0.00419660",
      "low_usd": 0.005617,
      "high_gbp": "0.0308",
      "high_usd": 0.041208,
      "bar_pct": 2,
      "market_cap_gbp_b": 0.032,
      "market_cap_usd_b": 0.042,
      "avg_volume_m": 5.71,
      "cmc_rank": 436,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 3669005,
      "vol_1w": 39996894,
      "vol_1m": 180406865,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "AIOZ",
      "yf_ticker": "AIOZ-USD",
      "company_name": "AIOZ Network",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.0377",
      "price_usd": 0.050468,
      "change_1d": "+1.37%",
      "change_1w": "-2.91%",
      "change_1m": "-12.08%",
      "change_ytd": "-41.75%",
      "return_1yr": "-42%",
      "low_gbp": "0.0374",
      "low_usd": 0.050008,
      "high_gbp": "0.3487",
      "high_usd": 0.466806,
      "bar_pct": 1,
      "market_cap_gbp_b": 0.048,
      "market_cap_usd_b": 0.064,
      "avg_volume_m": 3.51,
      "cmc_rank": 319,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 3527311,
      "vol_1w": 24604394,
      "vol_1m": 123682628,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "ARKM",
      "yf_ticker": "ARKM-USD",
      "company_name": "Arkham",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.0828",
      "price_usd": 0.11089,
      "change_1d": "+2.54%",
      "change_1w": "-1.61%",
      "change_1m": "-12.84%",
      "change_ytd": "-37.15%",
      "return_1yr": "-37%",
      "low_gbp": "0.0705",
      "low_usd": 0.09432,
      "high_gbp": "0.4967",
      "high_usd": 0.664888,
      "bar_pct": 3,
      "market_cap_gbp_b": 0.019,
      "market_cap_usd_b": 0.025,
      "avg_volume_m": 6.01,
      "cmc_rank": 628,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 5918593,
      "vol_1w": 42093190,
      "vol_1m": 221632613,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "WLD",
      "yf_ticker": "WLD-USD",
      "company_name": "Worldcoin",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.3071",
      "price_usd": 0.411017,
      "change_1d": "+4.49%",
      "change_1w": "+5.64%",
      "change_1m": "-18.23%",
      "change_ytd": "-14.56%",
      "return_1yr": "-15%",
      "low_gbp": "0.1747",
      "low_usd": 0.233905,
      "high_gbp": "1.45",
      "high_usd": 1.939647,
      "bar_pct": 10,
      "market_cap_gbp_b": 1.085,
      "market_cap_usd_b": 1.452,
      "avg_volume_m": 165.02,
      "cmc_rank": 45,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 245800667,
      "vol_1w": 1155162952,
      "vol_1m": 11461676894,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "NEAR",
      "yf_ticker": "NEAR-USD",
      "company_name": "NEAR Protocol",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "1.51",
      "price_usd": 2.019499,
      "change_1d": "+6.89%",
      "change_1w": "+0.49%",
      "change_1m": "-4.15%",
      "change_ytd": "+33.53%",
      "return_1yr": "+34%",
      "low_gbp": "0.7176",
      "low_usd": 0.960521,
      "high_gbp": "2.39",
      "high_usd": 3.196852,
      "bar_pct": 47,
      "market_cap_gbp_b": 1.963,
      "market_cap_usd_b": 2.627,
      "avg_volume_m": 156.02,
      "cmc_rank": 30,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 201356873,
      "vol_1w": 1092120819,
      "vol_1m": 7887654482,
      "news": [
        {
          "title": "NEAR Price May Rally 45% Amid Ongoing AI Crypto Resurge",
          "publisher": "FX Empire",
          "url": "https://finance.yahoo.com/markets/crypto/articles/near-price-may-rally-45-082914412.html",
          "published": 1784017754,
          "sentiment": 0.0
        },
        {
          "title": "Morning Minute: BTC and ETH ETFs Flip Green After Lengthy Outflow Stretch",
          "publisher": "decrypt",
          "url": "https://decrypt.co/373377/morning-minute-btc-and-eth-etfs-flip-green-after-lengthy-outflow-stretch",
          "published": 1783943591,
          "sentiment": 0.0
        },
        {
          "title": "HOOD Stock Drops Despite Price Target Hike \u2014 Robinhood Chain Beats ARB, HYPE, NEAR In DEX Trading",
          "publisher": "Stocktwits",
          "url": "https://stocktwits.com/news-articles/markets/cryptocurrency/hood-stock-rally-price-target-robinhood-chain-arb-hype-near/cZmr38WR78b",
          "published": 1783691186,
          "sentiment": 0.0
        }
      ],
      "news_sentiment": 0.0
    },
    {
      "ticker": "ICP",
      "yf_ticker": "ICP-USD",
      "company_name": "Internet Computer",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "1.66",
      "price_usd": 2.219106,
      "change_1d": "+2.39%",
      "change_1w": "+0.55%",
      "change_1m": "-8.47%",
      "change_ytd": "-21.72%",
      "return_1yr": "-22%",
      "low_gbp": "1.56",
      "low_usd": 2.084533,
      "high_gbp": "6.71",
      "high_usd": 8.982771,
      "bar_pct": 2,
      "market_cap_gbp_b": 0.919,
      "market_cap_usd_b": 1.23,
      "avg_volume_m": 40.12,
      "cmc_rank": 49,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 34854108,
      "vol_1w": 280814905,
      "vol_1m": 1367617794,
      "news": [
        {
          "title": "ICP Traders Pile $243 Million Into Multi/DEX Where Nobody Can Lose a Cent",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/icp-traders-pile-243-million-into-multi-dex/",
          "published": 1783943819,
          "sentiment": -0.402
        }
      ],
      "news_sentiment": -0.402
    },
    {
      "ticker": "KAITO",
      "yf_ticker": "KAITO-USD",
      "company_name": "Kaito",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.5786",
      "price_usd": 0.774479,
      "change_1d": "+11.27%",
      "change_1w": "+27.38%",
      "change_1m": "+66.09%",
      "change_ytd": "+53.00%",
      "return_1yr": "+53%",
      "low_gbp": "0.2175",
      "low_usd": 0.291124,
      "high_gbp": "1.30",
      "high_usd": 1.742911,
      "bar_pct": 33,
      "market_cap_gbp_b": 0.14,
      "market_cap_usd_b": 0.187,
      "avg_volume_m": 37.52,
      "cmc_rank": 131,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 28484015,
      "vol_1w": 262662037,
      "vol_1m": 670568646,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "VIRTUAL",
      "yf_ticker": "VIRTUAL-USD",
      "company_name": "Virtuals Protocol",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.4412",
      "price_usd": 0.590563,
      "change_1d": "+7.34%",
      "change_1w": "+10.57%",
      "change_1m": "-3.26%",
      "change_ytd": "-8.63%",
      "return_1yr": "-9%",
      "low_gbp": "0.3875",
      "low_usd": 0.518646,
      "high_gbp": "1.44",
      "high_usd": 1.927115,
      "bar_pct": 5,
      "market_cap_gbp_b": 0.29,
      "market_cap_usd_b": 0.388,
      "avg_volume_m": 71.72,
      "cmc_rank": 87,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 42902582,
      "vol_1w": 502060554,
      "vol_1m": 1607667889,
      "news": [],
      "news_sentiment": null
    }
  ]
};
