window.PRICES_DATA = {
  "updated": "2026-06-09 14:37",
  "fx_gbp_usd": 1.3403,
  "stocks": [
    {
      "ticker": "BTC",
      "yf_ticker": "BTC-USD",
      "company_name": "Bitcoin",
      "category": "bitcoin",
      "exchange": "Crypto",
      "price_gbp": "46555",
      "price_usd": 62397.323482,
      "change_1d": "-1.65%",
      "change_1w": "-9.43%",
      "change_1m": "-22.90%",
      "change_ytd": "-28.71%",
      "return_1yr": "-29%",
      "low_gbp": "45410",
      "high_gbp": "93095",
      "bar_pct": 2,
      "market_cap_gbp_b": 932.925,
      "avg_volume_m": 50945.94,
      "cmc_rank": 1,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 34027346086,
      "vol_1w": 356621564032,
      "vol_1m": 1103639689267,
      "news": [
        {
          "title": "Bitcoin (BTC USD) crashes 50% from October 2025 high, ETFs lose billions, and $1.8 billion gets liquidated - reasons why this crypto selloff is different from 2022 and 2018",
          "publisher": "economictimes.indiatimes.com",
          "url": "https://economictimes.indiatimes.com/news/international/us/bitcoin-btc-usd-crashes-50-from-october-2025-high-etfs-lose-billions-and-1-8-billion-gets-liquidated-reasons-why-this-crypto-selloff-is-different-from-2022-and-2018/articleshow/131590983.cms",
          "published": 1780934439,
          "sentiment": -0.225
        },
        {
          "title": "Strategy: You Don't Need A Bitcoin Bull Case For This To Work (Rating Upgrade) (NASDAQ:MSTR)",
          "publisher": "seekingalpha.com",
          "url": "https://seekingalpha.com/article/4912862-strategy-you-dont-need-a-bitcoin-bull-case-for-this-to-work-rating-upgrade",
          "published": 1780926395,
          "sentiment": 0.397
        }
      ],
      "news_sentiment": 0.086
    },
    {
      "ticker": "ETH",
      "yf_ticker": "ETH-USD",
      "company_name": "Ethereum",
      "category": "layer1",
      "exchange": "Crypto",
      "price_gbp": "1244",
      "price_usd": 1667.98359,
      "change_1d": "-1.23%",
      "change_1w": "-15.65%",
      "change_1m": "-28.35%",
      "change_ytd": "-43.78%",
      "return_1yr": "-44%",
      "low_gbp": "1170",
      "high_gbp": "3603",
      "bar_pct": 3,
      "market_cap_gbp_b": 150.192,
      "avg_volume_m": 23238.93,
      "cmc_rank": 2,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 16654264816,
      "vol_1w": 162672526903,
      "vol_1m": 470097673836,
      "news": [
        {
          "title": "Bitcoin and ethereum prices today, Monday, June 8, 2026: Moving up after bitcoin prices fell below $60,000",
          "publisher": "finance.yahoo.com",
          "url": "https://finance.yahoo.com/personal-finance/investing/article/bitcoin-and-ethereum-prices-today-monday-june-8-2026-moving-up-after-bitcoin-prices-fell-below-60000-131559331.html",
          "published": 1780924559,
          "sentiment": 0.0
        },
        {
          "title": "Bitcoin (BTC USD) price fell 15% and Ethereum (ETH USD) dropped to lowest level since April 2025 - here are the reasons why crypto market is crashing this week",
          "publisher": "economictimes.indiatimes.com",
          "url": "https://economictimes.indiatimes.com/news/international/us/bitcoin-btc-usd-price-fell-15-and-ethereum-eth-usd-dropped-to-lowest-level-since-april-2025-here-are-the-reasons-why-crypto-market-is-crashing-this-week/articleshow/131535141.cms",
          "published": 1780673297,
          "sentiment": -0.58
        }
      ],
      "news_sentiment": -0.29
    },
    {
      "ticker": "SOL",
      "yf_ticker": "SOL-USD",
      "company_name": "Solana",
      "category": "layer1",
      "exchange": "Crypto",
      "price_gbp": "49",
      "price_usd": 65.67651,
      "change_1d": "-1.69%",
      "change_1w": "-16.91%",
      "change_1m": "-29.86%",
      "change_ytd": "-47.25%",
      "return_1yr": "-47%",
      "low_gbp": "46",
      "high_gbp": "185",
      "bar_pct": 2,
      "market_cap_gbp_b": 28.391,
      "avg_volume_m": 4300.91,
      "cmc_rank": 7,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 3259028211,
      "vol_1w": 30106357256,
      "vol_1m": 93585140596,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "BNB",
      "yf_ticker": "BNB-USD",
      "company_name": "BNB",
      "category": "layer1",
      "exchange": "Crypto",
      "price_gbp": "443",
      "price_usd": 594.164172,
      "change_1d": "-1.09%",
      "change_1w": "-11.99%",
      "change_1m": "-8.68%",
      "change_ytd": "-31.16%",
      "return_1yr": "-31%",
      "low_gbp": "427",
      "high_gbp": "979",
      "bar_pct": 3,
      "market_cap_gbp_b": 59.751,
      "avg_volume_m": 1441.73,
      "cmc_rank": 4,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 770856290,
      "vol_1w": 10092076226,
      "vol_1m": 35315509141,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "ADA",
      "yf_ticker": "ADA-USD",
      "company_name": "Cardano",
      "category": "layer1",
      "exchange": "Crypto",
      "price_gbp": "0.1250",
      "price_usd": 0.167513,
      "change_1d": "+0.83%",
      "change_1w": "-24.97%",
      "change_1m": "-38.69%",
      "change_ytd": "-49.65%",
      "return_1yr": "-50%",
      "low_gbp": "0.1169",
      "high_gbp": "0.7187",
      "bar_pct": 1,
      "market_cap_gbp_b": 4.529,
      "avg_volume_m": 762.83,
      "cmc_rank": 15,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 517340683,
      "vol_1w": 5339785395,
      "vol_1m": 13904100217,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "AVAX",
      "yf_ticker": "AVAX-USD",
      "company_name": "Avalanche",
      "category": "layer1",
      "exchange": "Crypto",
      "price_gbp": "4.98",
      "price_usd": 6.676234,
      "change_1d": "-0.87%",
      "change_1w": "-23.24%",
      "change_1m": "-33.38%",
      "change_ytd": "-45.76%",
      "return_1yr": "-46%",
      "low_gbp": "4.97",
      "high_gbp": "26",
      "bar_pct": 1,
      "market_cap_gbp_b": 2.151,
      "avg_volume_m": 290.24,
      "cmc_rank": 27,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 228316959,
      "vol_1w": 2031708492,
      "vol_1m": 6476401516,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "XRP",
      "yf_ticker": "XRP-USD",
      "company_name": "XRP",
      "category": "payments",
      "exchange": "Crypto",
      "price_gbp": "0.8634",
      "price_usd": 1.157243,
      "change_1d": "-0.35%",
      "change_1w": "-8.47%",
      "change_1m": "-19.17%",
      "change_ytd": "-37.08%",
      "return_1yr": "-37%",
      "low_gbp": "0.8156",
      "high_gbp": "2.65",
      "bar_pct": 3,
      "market_cap_gbp_b": 53.579,
      "avg_volume_m": 2773.85,
      "cmc_rank": 6,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 2132633734,
      "vol_1w": 19416926968,
      "vol_1m": 63576621893,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "XLM",
      "yf_ticker": "XLM-USD",
      "company_name": "Stellar",
      "category": "payments",
      "exchange": "Crypto",
      "price_gbp": "0.1479",
      "price_usd": 0.198164,
      "change_1d": "-2.08%",
      "change_1w": "-14.46%",
      "change_1m": "+20.95%",
      "change_ytd": "-1.23%",
      "return_1yr": "-1%",
      "low_gbp": "0.1070",
      "high_gbp": "0.3753",
      "bar_pct": 15,
      "market_cap_gbp_b": 4.988,
      "avg_volume_m": 734.85,
      "cmc_rank": 13,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 325788510,
      "vol_1w": 5143963284,
      "vol_1m": 15851669179,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "TRX",
      "yf_ticker": "TRX-USD",
      "company_name": "TRON",
      "category": "payments",
      "exchange": "Crypto",
      "price_gbp": "0.2402",
      "price_usd": 0.321919,
      "change_1d": "-1.40%",
      "change_1w": "-5.62%",
      "change_1m": "-8.33%",
      "change_ytd": "+13.21%",
      "return_1yr": "+13%",
      "low_gbp": "0.1967",
      "high_gbp": "0.2801",
      "bar_pct": 52,
      "market_cap_gbp_b": 22.776,
      "avg_volume_m": 686.68,
      "cmc_rank": 8,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 484994014,
      "vol_1w": 4806774346,
      "vol_1m": 17122597379,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "SUI",
      "yf_ticker": "SUI20947-USD",
      "company_name": "Sui",
      "category": "emerging",
      "exchange": "Crypto",
      "price_gbp": "0.5603",
      "price_usd": 0.750932,
      "change_1d": "-1.34%",
      "change_1w": "-11.72%",
      "change_1m": "-33.42%",
      "change_ytd": "-46.46%",
      "return_1yr": "-46%",
      "low_gbp": "0.5223",
      "high_gbp": "3.23",
      "bar_pct": 1,
      "market_cap_gbp_b": 2.257,
      "avg_volume_m": 744.64,
      "cmc_rank": 26,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 492861967,
      "vol_1w": 5212450089,
      "vol_1m": 24653059430,
      "news": [
        {
          "title": "Why Is The Crypto Market Down Today?",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/why-is-the-crypto-market-down-today/",
          "published": 1780980561,
          "sentiment": 0.0
        }
      ],
      "news_sentiment": 0.0
    },
    {
      "ticker": "HBAR",
      "yf_ticker": "HBAR-USD",
      "company_name": "Hedera",
      "category": "emerging",
      "exchange": "Crypto",
      "price_gbp": "0.0599",
      "price_usd": 0.080304,
      "change_1d": "-2.15%",
      "change_1w": "-10.78%",
      "change_1m": "-15.64%",
      "change_ytd": "-24.38%",
      "return_1yr": "-24%",
      "low_gbp": "0.0585",
      "high_gbp": "0.2169",
      "bar_pct": 1,
      "market_cap_gbp_b": 2.599,
      "avg_volume_m": 98.12,
      "cmc_rank": 24,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 52256420,
      "vol_1w": 686826331,
      "vol_1m": 3105578541,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "TON",
      "yf_ticker": "TON11419-USD",
      "company_name": "Toncoin",
      "category": "emerging",
      "exchange": "Crypto",
      "price_gbp": "1.29",
      "price_usd": 1.730548,
      "change_1d": "-0.29%",
      "change_1w": "-14.54%",
      "change_1m": "-27.68%",
      "change_ytd": "+4.49%",
      "return_1yr": "+4%",
      "low_gbp": "0.8965",
      "high_gbp": "2.67",
      "bar_pct": 22,
      "market_cap_gbp_b": 3.454,
      "avg_volume_m": 313.53,
      "cmc_rank": 19,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 222342618,
      "vol_1w": 2194704854,
      "vol_1m": 9601452378,
      "news": [
        {
          "title": "Nasdaq TON Whale Locks 226 Million Tokens as Yield Jumps",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/ton-strategy-staking-yield-jumps/",
          "published": 1780995613,
          "sentiment": 0.0
        },
        {
          "title": "TON Strategy Reports Higher May Staking Yield as Network Upgrades Go Live",
          "publisher": "CryptoProwl",
          "url": "https://www.cryptoprowl.com/releases/ton-strategy-reports-higher-may-staking-yield-as-network-upgrades-go-live-5807",
          "published": 1780935900,
          "sentiment": 0.0
        }
      ],
      "news_sentiment": 0.0
    },
    {
      "ticker": "ALGO",
      "yf_ticker": "ALGO-USD",
      "company_name": "Algorand",
      "category": "emerging",
      "exchange": "Crypto",
      "price_gbp": "0.0686",
      "price_usd": 0.091881,
      "change_1d": "-2.75%",
      "change_1w": "-23.09%",
      "change_1m": "-28.15%",
      "change_ytd": "-16.61%",
      "return_1yr": "-17%",
      "low_gbp": "0.0605",
      "high_gbp": "0.2396",
      "bar_pct": 5,
      "market_cap_gbp_b": 0.612,
      "avg_volume_m": 47.07,
      "cmc_rank": 62,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 32680634,
      "vol_1w": 329522161,
      "vol_1m": 1292962801,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "MINA",
      "yf_ticker": "MINA-USD",
      "company_name": "Mina",
      "category": "emerging",
      "exchange": "Crypto",
      "price_gbp": "0.0316",
      "price_usd": 0.042412,
      "change_1d": "-2.96%",
      "change_1w": "-22.73%",
      "change_1m": "-35.90%",
      "change_ytd": "-43.86%",
      "return_1yr": "-44%",
      "low_gbp": "0.0316",
      "high_gbp": "0.1775",
      "bar_pct": 1,
      "market_cap_gbp_b": 0.041,
      "avg_volume_m": 33.47,
      "cmc_rank": 375,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 6313895,
      "vol_1w": 234281111,
      "vol_1m": 330239281,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "POL",
      "yf_ticker": "POL-USD",
      "company_name": "Polygon (MATIC)",
      "category": "infra",
      "exchange": "Crypto",
      "price_gbp": "0.0562",
      "price_usd": 0.075382,
      "change_1d": "-6.92%",
      "change_1w": "-17.98%",
      "change_1m": "-26.65%",
      "change_ytd": "-24.95%",
      "return_1yr": "-25%",
      "low_gbp": "0.0577",
      "high_gbp": "0.2159",
      "bar_pct": 1,
      "market_cap_gbp_b": 0.599,
      "avg_volume_m": 66.84,
      "cmc_rank": 63,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 40441902,
      "vol_1w": 467868636,
      "vol_1m": 1436626682,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "DOT",
      "yf_ticker": "DOT-USD",
      "company_name": "Polkadot",
      "category": "infra",
      "exchange": "Crypto",
      "price_gbp": "0.7212",
      "price_usd": 0.966675,
      "change_1d": "-0.80%",
      "change_1w": "-15.08%",
      "change_1m": "-29.14%",
      "change_ytd": "-45.99%",
      "return_1yr": "-46%",
      "low_gbp": "0.7022",
      "high_gbp": "3.39",
      "bar_pct": 1,
      "market_cap_gbp_b": 1.217,
      "avg_volume_m": 157.19,
      "cmc_rank": 43,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 94585783,
      "vol_1w": 1100310512,
      "vol_1m": 4804842571,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "LINK",
      "yf_ticker": "LINK-USD",
      "company_name": "Chainlink",
      "category": "infra",
      "exchange": "Crypto",
      "price_gbp": "5.88",
      "price_usd": 7.885753,
      "change_1d": "-1.21%",
      "change_1w": "-10.89%",
      "change_1m": "-25.33%",
      "change_ytd": "-35.33%",
      "return_1yr": "-35%",
      "low_gbp": "5.48",
      "high_gbp": "20",
      "bar_pct": 3,
      "market_cap_gbp_b": 4.278,
      "avg_volume_m": 420.93,
      "cmc_rank": 17,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 299022760,
      "vol_1w": 2946506159,
      "vol_1m": 10307627752,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "DOGE",
      "yf_ticker": "DOGE-USD",
      "company_name": "Dogecoin",
      "category": "meme",
      "exchange": "Crypto",
      "price_gbp": "0.0637",
      "price_usd": 0.085416,
      "change_1d": "-1.13%",
      "change_1w": "-13.45%",
      "change_1m": "-21.08%",
      "change_ytd": "-27.17%",
      "return_1yr": "-27%",
      "low_gbp": "0.0607",
      "high_gbp": "0.2159",
      "bar_pct": 2,
      "market_cap_gbp_b": 9.852,
      "avg_volume_m": 1186.55,
      "cmc_rank": 10,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 658632418,
      "vol_1w": 8305878237,
      "vol_1m": 31291207047,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "PEPE",
      "yf_ticker": "PEPE24478-USD",
      "company_name": "Pepe",
      "category": "meme",
      "exchange": "Crypto",
      "price_gbp": "0.00000208",
      "price_usd": 3e-06,
      "change_1d": "-1.29%",
      "change_1w": "-16.51%",
      "change_1m": "-34.71%",
      "change_ytd": "-30.95%",
      "return_1yr": "-31%",
      "low_gbp": "0.00000200",
      "high_gbp": "0.00001058",
      "bar_pct": 1,
      "market_cap_gbp_b": 0.86,
      "avg_volume_m": 259.99,
      "cmc_rank": 52,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 172580786,
      "vol_1w": 1819936101,
      "vol_1m": 6478501541,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "TAO",
      "yf_ticker": "TAO-USD",
      "company_name": "Bittensor",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "160",
      "price_usd": 214.507178,
      "change_1d": "-0.06%",
      "change_1w": "-13.85%",
      "change_1m": "-32.37%",
      "change_ytd": "-1.90%",
      "return_1yr": "-2%",
      "low_gbp": "109",
      "high_gbp": "372",
      "bar_pct": 20,
      "market_cap_gbp_b": 1.76,
      "avg_volume_m": 239.54,
      "cmc_rank": 34,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 152627856,
      "vol_1w": 1676792166,
      "vol_1m": 6396944813,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "FET",
      "yf_ticker": "FET-USD",
      "company_name": "ASI Alliance",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.1523",
      "price_usd": 0.204088,
      "change_1d": "-4.40%",
      "change_1w": "-25.45%",
      "change_1m": "-12.88%",
      "change_ytd": "+2.71%",
      "return_1yr": "+3%",
      "low_gbp": "0.1054",
      "high_gbp": "0.6285",
      "bar_pct": 9,
      "market_cap_gbp_b": 0.344,
      "avg_volume_m": 159.24,
      "cmc_rank": 84,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 81466363,
      "vol_1w": 1114678967,
      "vol_1m": 3782556138,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "RNDR",
      "yf_ticker": "RNDR-USD",
      "company_name": "Render",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "1.22",
      "price_usd": 1.635936,
      "change_1d": "-2.70%",
      "change_1w": "-25.66%",
      "change_1m": "-18.61%",
      "change_ytd": "+27.40%",
      "return_1yr": "+27%",
      "low_gbp": "0.9025",
      "high_gbp": "3.42",
      "bar_pct": 13,
      "market_cap_gbp_b": 0.633,
      "avg_volume_m": 122.89,
      "cmc_rank": 61,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 68616538,
      "vol_1w": 860219186,
      "vol_1m": 3068304809,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "OCEAN",
      "yf_ticker": "OCEAN-USD",
      "company_name": "Ocean Protocol",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.0789",
      "price_usd": 0.10574,
      "change_1d": "-2.16%",
      "change_1w": "-20.26%",
      "change_1m": "-15.34%",
      "change_ytd": "-29.78%",
      "return_1yr": "-30%",
      "low_gbp": "0.0756",
      "high_gbp": "0.2749",
      "bar_pct": 2,
      "market_cap_gbp_b": null,
      "avg_volume_m": 0.12,
      "cmc_rank": 4233,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 61386,
      "vol_1w": 854587,
      "vol_1m": 3096395,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "GRT",
      "yf_ticker": "GRT-USD",
      "company_name": "The Graph",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.0149",
      "price_usd": 0.019943,
      "change_1d": "-1.27%",
      "change_1w": "-19.72%",
      "change_1m": "-28.73%",
      "change_ytd": "-40.01%",
      "return_1yr": "-40%",
      "low_gbp": "0.0148",
      "high_gbp": "0.0866",
      "bar_pct": 1,
      "market_cap_gbp_b": 0.161,
      "avg_volume_m": 18.71,
      "cmc_rank": 125,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 8898687,
      "vol_1w": 130936197,
      "vol_1m": 637538458,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "AGIX",
      "yf_ticker": "AGIX-USD",
      "company_name": "SingularityNET",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.0674",
      "price_usd": 0.090273,
      "change_1d": "-3.43%",
      "change_1w": "-23.95%",
      "change_1m": "-10.47%",
      "change_ytd": "+5.28%",
      "return_1yr": "+5%",
      "low_gbp": "0.0133",
      "high_gbp": "0.2726",
      "bar_pct": 21,
      "market_cap_gbp_b": null,
      "avg_volume_m": 0.04,
      "cmc_rank": 4505,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 12423,
      "vol_1w": 252957,
      "vol_1m": 811354,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "NMR",
      "yf_ticker": "NMR-USD",
      "company_name": "Numeraire",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "6.36",
      "price_usd": 8.520627,
      "change_1d": "+3.39%",
      "change_1w": "+0.25%",
      "change_1m": "-6.10%",
      "change_ytd": "-10.82%",
      "return_1yr": "-11%",
      "low_gbp": "4.70",
      "high_gbp": "16",
      "bar_pct": 15,
      "market_cap_gbp_b": 0.048,
      "avg_volume_m": 7.3,
      "cmc_rank": 330,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 5028115,
      "vol_1w": 51119393,
      "vol_1m": 268192476,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "ALT",
      "yf_ticker": "ALT-USD",
      "company_name": "AltLayer",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.00445395",
      "price_usd": 0.00597,
      "change_1d": "+3.56%",
      "change_1w": "-14.79%",
      "change_1m": "-27.03%",
      "change_ytd": "-47.86%",
      "return_1yr": "-48%",
      "low_gbp": "0.00422695",
      "high_gbp": "0.0307",
      "bar_pct": 1,
      "market_cap_gbp_b": 0.029,
      "avg_volume_m": 8.47,
      "cmc_rank": 481,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 5261516,
      "vol_1w": 59293021,
      "vol_1m": 831385628,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "AIOZ",
      "yf_ticker": "AIOZ-USD",
      "company_name": "AIOZ Network",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.0425",
      "price_usd": 0.056933,
      "change_1d": "-2.53%",
      "change_1w": "-12.63%",
      "change_1m": "-23.85%",
      "change_ytd": "-34.29%",
      "return_1yr": "-34%",
      "low_gbp": "0.0387",
      "high_gbp": "0.3483",
      "bar_pct": 1,
      "market_cap_gbp_b": 0.053,
      "avg_volume_m": 5.15,
      "cmc_rank": 302,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 4742338,
      "vol_1w": 36028409,
      "vol_1m": 159938742,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "ARKM",
      "yf_ticker": "ARKM-USD",
      "company_name": "Arkham",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.0910",
      "price_usd": 0.121971,
      "change_1d": "+0.79%",
      "change_1w": "-17.29%",
      "change_1m": "-13.10%",
      "change_ytd": "-30.87%",
      "return_1yr": "-31%",
      "low_gbp": "0.0704",
      "high_gbp": "0.4961",
      "bar_pct": 5,
      "market_cap_gbp_b": 0.02,
      "avg_volume_m": 16.76,
      "cmc_rank": 615,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 15574190,
      "vol_1w": 117345969,
      "vol_1m": 475486384,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "WLD",
      "yf_ticker": "WLD-USD",
      "company_name": "Worldcoin",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.3933",
      "price_usd": 0.52716,
      "change_1d": "+10.18%",
      "change_1w": "+25.28%",
      "change_1m": "+93.98%",
      "change_ytd": "+9.59%",
      "return_1yr": "+10%",
      "low_gbp": "0.1745",
      "high_gbp": "1.45",
      "bar_pct": 17,
      "market_cap_gbp_b": 1.333,
      "avg_volume_m": 899.01,
      "cmc_rank": 37,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 624349244,
      "vol_1w": 6293090942,
      "vol_1m": 10815614130,
      "news": [
        {
          "title": "Arthur Hayes Bets The AI Bubble Will Pop And Drag Bitcoin Down \u2014 Here's Why He Dumped HYPE, NEAR, ZEC And WLD",
          "publisher": "Stocktwits",
          "url": "https://stocktwits.com/news-articles/markets/cryptocurrency/arthur-hayes-ai-bubble-will-pop-btc-eth-hype-zec-near/cZ0UXT2R7b6",
          "published": 1781010711,
          "sentiment": -0.557
        },
        {
          "title": "As OpenAI files for IPO, Sam Altman\u2019s eye-scanning company is doing layoffs, report says",
          "publisher": "TechCrunch",
          "url": "https://finance.yahoo.com/markets/stocks/articles/openai-files-ipo-sam-altman-224145119.html",
          "published": 1780958505,
          "sentiment": 0.0
        },
        {
          "title": "Why are Altcoins Suddenly Exploding? Two Forces are Driving the Move",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/altcoins-rally-after-bitcoin-crash-analysis/",
          "published": 1780945864,
          "sentiment": 0.0
        },
        {
          "title": "Arthur Hayes Cashes Out Of Worldcoin Days After Backing Sam Altman\u2019s Token",
          "publisher": "Stocktwits",
          "url": "https://stocktwits.com/news-articles/markets/cryptocurrency/arthur-hayes-cashes-out-of-worldcoin-days-after-backing-sam-altman-s-token/cZ0pMmJRe6d",
          "published": 1780755913,
          "sentiment": 0.026
        },
        {
          "title": "Arthur Hayes Sparks Fury After Abrupt Worldcoin Exit, WLD Price Falls 10%",
          "publisher": "BeInCrypto",
          "url": "https://beincrypto.com/arthur-hayes-worldcoin-wld-exit-backlash/",
          "published": 1780736909,
          "sentiment": -0.572
        }
      ],
      "news_sentiment": -0.221
    },
    {
      "ticker": "NEAR",
      "yf_ticker": "NEAR-USD",
      "company_name": "NEAR Protocol",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "1.60",
      "price_usd": 2.1399,
      "change_1d": "-0.23%",
      "change_1w": "-20.91%",
      "change_1m": "+36.28%",
      "change_ytd": "+41.49%",
      "return_1yr": "+41%",
      "low_gbp": "0.7167",
      "high_gbp": "2.39",
      "bar_pct": 53,
      "market_cap_gbp_b": 2.072,
      "avg_volume_m": 916.67,
      "cmc_rank": 29,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 598567096,
      "vol_1w": 6416691201,
      "vol_1m": 20077900341,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "ICP",
      "yf_ticker": "ICP-USD",
      "company_name": "Internet Computer",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "1.72",
      "price_usd": 2.304206,
      "change_1d": "-3.54%",
      "change_1w": "-26.10%",
      "change_1m": "-32.38%",
      "change_ytd": "-18.72%",
      "return_1yr": "-19%",
      "low_gbp": "1.56",
      "high_gbp": "6.70",
      "bar_pct": 3,
      "market_cap_gbp_b": 0.951,
      "avg_volume_m": 118.92,
      "cmc_rank": 49,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 54144243,
      "vol_1w": 832407809,
      "vol_1m": 2760949923,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "KAITO",
      "yf_ticker": "KAITO-USD",
      "company_name": "Kaito",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.3049",
      "price_usd": 0.408699,
      "change_1d": "-9.75%",
      "change_1w": "-10.91%",
      "change_1m": "-19.84%",
      "change_ytd": "-19.26%",
      "return_1yr": "-19%",
      "low_gbp": "0.2172",
      "high_gbp": "1.33",
      "bar_pct": 8,
      "market_cap_gbp_b": 0.074,
      "avg_volume_m": 14.18,
      "cmc_rank": 183,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 10218034,
      "vol_1w": 99253291,
      "vol_1m": 510477250,
      "news": [],
      "news_sentiment": null
    },
    {
      "ticker": "VIRTUAL",
      "yf_ticker": "VIRTUAL-USD",
      "company_name": "Virtuals Protocol",
      "category": "ai",
      "exchange": "Crypto",
      "price_gbp": "0.4324",
      "price_usd": 0.579565,
      "change_1d": "-1.27%",
      "change_1w": "-23.50%",
      "change_1m": "-36.54%",
      "change_ytd": "-10.34%",
      "return_1yr": "-10%",
      "low_gbp": "0.3870",
      "high_gbp": "1.58",
      "bar_pct": 4,
      "market_cap_gbp_b": 0.284,
      "avg_volume_m": 110.28,
      "cmc_rank": 93,
      "beta": null,
      "pe_ratio": null,
      "div_yield_pct": null,
      "short_pct": null,
      "analyst": null,
      "analyst_score": null,
      "vol_1d": 90810912,
      "vol_1w": 771935405,
      "vol_1m": 2675336526,
      "news": [],
      "news_sentiment": null
    }
  ]
};
